# 데이터 전처리

## 🔧 데이터 전처리 (Data Preprocessing) 란?

데이터 전처리는 원시 데이터를 AI 모델이 학습하기 좋은 형태로 변환하는 과정입니다.  
실무에서는 전체 AI 프로젝트 시간의 약 80%를 차지하는 핵심 단계입니다.

**⚠️ "Garbage In, Garbage Out"**  
의료 분야에서는 환자 안전과 직결되므로 특히 신중한 전처리가 필요합니다.

## 🔄 데이터 전처리 로드맵

### **1단계: 데이터 정제 (Data Cleaning)**
→ 더러운 데이터를 깨끗하게 만들기
- 결측치 탐지 및 처리
- 중복 데이터 탐지 및 제거
- 이상치 탐지 및 처리  
- 데이터 타입 확인 및 변환

### **2단계: 기본 변환 (Basic Transformation)**
→ 깨끗한 데이터를 AI 모델이 학습하기 좋은 형태로 변환
- 데이터 인코딩 (원핫 인코딩/라벨 인코딩)
- 데이터 스케일링

## 데이터 정제 (Data Cleaning)

**데이터 정제(Data Cleansing)는** 전처리의 첫 번째이자 가장 중요한 단계로, 더러운 데이터를 깨끗하게 만드는 작업입니다.  
결측치, 중복, 이상치 등의 품질 문제를 해결하여 AI가 이해하기 쉬운 형태로 바꿔줍니다.

### 결측치 탐지 및 처리

#### 결측치란?

결측치(Missing Values)는 어떤 이유로 인해 값이 누락된 데이터(NaN, None, Null)를 의미합니다.

**결측치가 AI 모델링에 미치는 문제**  
결측치가 있으면 AI 모델이 학습을 시작조차 할 수 없습니다. 대부분의 머신러닝 알고리즘은 완전한 숫자 데이터만 처리 가능하기 때문입니다.  

**예를 들어** 환자의 혈압 데이터가 누락된 상태로 심혈관 질환 예측 모델을 학습시키면, 잘못된 예측이 나올 수 있어 진단 오류로 이어질 수 있습니다.

**결측치가 생기는 이유**
- **측정 실패**: 기기 오작동, 검사 거부
- **데이터 입력 누락**: 인적 오류, 시스템 장애  
- **의도적 생략**: 개인정보 보호, 해당없음 응답
- **데이터 병합 과정**: 서로 다른 데이터베이스 통합 시


#### 결측치 확인하기

In [ ]:
# 데이터 분석 및 처리용 라이브러리
import pandas as pd
import numpy as np

print(f"Pandas 버전: {pd.__version__}")
print(f"Numpy 버전: {np.__version__}")

Pandas 버전: 2.2.2
Numpy 버전: 2.0.2

In [ ]:


# 실습용 환자 데이터 생성
patient_data = {
    'PatientID': ['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P009', 'P010'],
    'Age': [25, 34, None, 45, 52, np.nan, 67, 23, 41, 58],
    'BMI': [22.5, None, 28.3, 31.2, 24.8, 29.1, np.nan, 21.3, 26.7, 33.4],
    'BloodPressure': [120, 130, 125, None, 140, 135, 150, 118, np.nan, 160],
    'Diabetes': [0, 1, 0, np.nan, 1, 1, 1, 0, 0, 1],
    'Income': [50, 60, 45, 70, None, 55, 80, 40, 65, np.nan]
}
df_patients = pd.DataFrame(patient_data)

print(f"\n데이터 크기: {df_patients.shape}")

df_patients

데이터 크기: (10, 6)

  PatientID   Age   BMI  BloodPressure  Diabetes  Income
0      P001  25.0  22.5          120.0       0.0    50.0
1      P002  34.0   NaN          130.0       1.0    60.0
2      P003   NaN  28.3          125.0       0.0    45.0
3      P004  45.0  31.2            NaN       NaN    70.0
4      P005  52.0  24.8          140.0       1.0     NaN
5      P006   NaN  29.1          135.0       1.0    55.0
6      P007  67.0   NaN          150.0       1.0    80.0
7      P008  23.0  21.3          118.0       0.0    40.0
8      P009  41.0  26.7            NaN       0.0    65.0
9      P010  58.0  33.4          160.0       1.0     NaN

#### 결측치 탐지 방법

**1. isnull() - 결측치 확인**
- **기능**: 결측치 위치를 True/False로 표시
- **반환값**: 불린(Boolean) DataFrame/Series
- **참고**: isna()도 동일한 기능이지만 isnull()이 더 널리 사용됨

In [ ]:
# 결측치 확인
missing_check = df_patients.isnull()  # True가 결측치
print("결측치 확인 결과:")

missing_check

결측치 확인 결과:

   PatientID    Age    BMI  BloodPressure  Diabetes  Income
0      False  False  False          False     False   False
1      False  False   True          False     False   False
2      False   True  False          False     False   False
3      False  False  False           True      True   False
4      False  False  False          False     False    True
5      False   True  False          False     False   False
6      False  False   True          False     False   False
7      False  False  False          False     False   False
8      False  False  False           True     False   False
9      False  False  False          False     False    True

In [ ]:
# 컬럼별 결측치 개수
missing_count = df_patients.isnull().sum()  # Series반환 (True=1, False=0으로 계산)
print("컬럼별 결측치 개수:")
print(missing_count)

# 전체 결측치 개수
total_missing = df_patients.isnull().sum().sum()   # 모든 결측치 데이터 합산
print(f"전체 결측치: {total_missing}개")

# 결측치 비율 계산
missing_ratio = (missing_count / len(df_patients)) * 100
print("\n컬럼별 결측치 비율:")
for col, ratio in missing_ratio.items():
    print(f"{col}: {ratio:.1f}%")

컬럼별 결측치 개수:
PatientID        0
Age              2
BMI              2
BloodPressure    2
Diabetes         1
Income           2
dtype: int64
전체 결측치: 9개

컬럼별 결측치 비율:
PatientID: 0.0%
Age: 20.0%
BMI: 20.0%
BloodPressure: 20.0%
Diabetes: 10.0%
Income: 20.0%

**2. notnull() - 정상값 확인**
- **기능**: 정상값(결측치가 아닌 값) 위치를 True/False로 표시 (False가 결측치)
- **활용**: 정상 데이터만 필터링할 때 사용
- **참고**: notna()도 동일한 기능이지만 notnull()이 더 널리 사용됨

In [ ]:
# 정상값 확인
valid_check = df_patients.notnull()    # False가 결측치
print("정상값이 있는 위치:")

valid_check.head()

In [ ]:
# 특정 컬럼 기준 정상 데이터만 필터링
valid_age_patients = df_patients[df_patients['Age'].notnull()]
print(f"\n나이 정보가 있는 환자: {len(valid_age_patients)}명")    # 행 갯수 출력

valid_age_patients

나이 정보가 있는 환자: 8명

  PatientID   Age   BMI  BloodPressure  Diabetes  Income
0      P001  25.0  22.5          120.0       0.0    50.0
1      P002  34.0   NaN          130.0       1.0    60.0
3      P004  45.0  31.2            NaN       NaN    70.0
4      P005  52.0  24.8          140.0       1.0     NaN
6      P007  67.0   NaN          150.0       1.0    80.0
7      P008  23.0  21.3          118.0       0.0    40.0
8      P009  41.0  26.7            NaN       0.0    65.0
9      P010  58.0  33.4          160.0       1.0     NaN

In [ ]:
# 여러 컬럼 기준 정상 데이터만 필터링
valid_patients = df_patients[df_patients['Age'].notnull() & df_patients['BMI'].notnull()]
print(f"\나이, BMI 정보가 있는 환자: {len(valid_patients)}명")

valid_patients

\나이, BMI 정보가 있는 환자: 6명

  PatientID   Age   BMI  BloodPressure  Diabetes  Income
0      P001  25.0  22.5          120.0       0.0    50.0
3      P004  45.0  31.2            NaN       NaN    70.0
4      P005  52.0  24.8          140.0       1.0     NaN
7      P008  23.0  21.3          118.0       0.0    40.0
8      P009  41.0  26.7            NaN       0.0    65.0
9      P010  58.0  33.4          160.0       1.0     NaN

**3. 결측치 패턴 분석**
- **any(axis=1)**: 각 행에 결측치가 하나라도 있는지 확인
- **all()**: 모든 값이 결측치인 컬럼 확인

In [ ]:
# 각 환자별 결측치 보유 여부
rows_with_missing = df_patients.isnull().any(axis=1)    # 불린 Series 반환, 한개라도 결측치 있다면 True
missing_patients = df_patients[rows_with_missing]       # DataFrame 반환, 결측치가 있는 환자들만 필터링

print(f"결측치가 있는 환자: {len(missing_patients)}")

missing_patients[['PatientID']]

결측치가 있는 환자: 8

  PatientID
1      P002
2      P003
3      P004
4      P005
5      P006
6      P007
8      P009
9      P010

In [ ]:

# 완전히 비어있는 컬럼 확인
cols_all_missing = df_patients.isnull().all()          # 불린 Series 반환, 모든 값이 결측이라면 True
empty_cols = cols_all_missing[cols_all_missing]        # DataFrame 반환, 모든 값이 결측인 환자들만 필터링
print(f"\n모든 값이 결측인 컬럼: {len(empty_cols)}개")

모든 값이 결측인 컬럼: 0개

In [ ]:
# 완전한 데이터를 가진 환자
complete_patients = df_patients[~rows_with_missing]    # NOT 연산자로 필터링된 DataFrame 반환
print(f"완전한 데이터 환자: {len(complete_patients)}명")

complete_patients['PatientID']

완전한 데이터 환자: 2명

0    P001
7    P008
Name: PatientID, dtype: object

#### 결측치 처리 방법

##### 결측치가 있는 행/열 삭제

```dropna()``` 메서드

- **기본 문법**: `df.dropna()`

- **주요 파라미터**:
  - `axis=0` (행 삭제, 기본값), `axis=1` (열 삭제)
  - `subset=['컬럼명']` (특정 컬럼 기준)
  - `thresh=숫자` (최소 유효값 개수)
  - `inplace=False` (기본값): 새로운 DataFrame 반환, 원본 유지
  - `inplace=True`: 원본 DataFrame 직접 수정하고 `None` 반환

In [ ]:
# 방법 1: 모든 결측치 행 삭제
df_dropna_all = df_patients.dropna()
print(f"전체 삭제: {len(df_patients)}명 → {len(df_dropna_all)}명")

전체 삭제: 10명 → 2명

In [ ]:
# 방법 2: 특정 컬럼만 고려한 행 삭제 ⭐️
key_columns = ['Age', 'BMI', 'Diabetes']
df_dropna_subset = df_patients.dropna(subset=key_columns)
print(f"핵심 컬럼({key_columns}) 기준: {len(df_dropna_subset)}명")

print("\n삭제 후 남은 환자들:")
print(df_dropna_subset[['PatientID', 'Age', 'BMI', 'Diabetes']])

핵심 컬럼(['Age', 'BMI', 'Diabetes']) 기준: 5명

삭제 후 남은 환자들:
  PatientID   Age   BMI  Diabetes
0      P001  25.0  22.5       0.0
4      P005  52.0  24.8       1.0
7      P008  23.0  21.3       0.0
8      P009  41.0  26.7       0.0
9      P010  58.0  33.4       1.0

In [ ]:
# 방법 3: 결측치 있는 컬럼 삭제
df_dropna_col = df_patients.dropna(axis=1)
df_dropna_col

  PatientID
0      P001
1      P002
2      P003
3      P004
4      P005
5      P006
6      P007
7      P008
8      P009
9      P010

In [ ]:
# 방법 3: 최소 유효값 개수 기준
valid_count = 5
df_dropna_thresh = df_patients.dropna(thresh=valid_count)  # 최소 5개 유효값 필요
print(f"최소 {valid_count}개 유효값 기준: {len(df_dropna_thresh)}명")

# 예시 (thresh=3)
# 환자 A: [25, NaN, 120, 1, NaN]     → 유효값 3개 → 유지 ✅
# 환자 B: [NaN, NaN, NaN, NaN, 50]   → 유효값 1개 → 삭제 ❌
# 환자 C: [30, 25.5, 130, 0, 60]     → 유효값 5개 → 유지 ✅

최소 5개 유효값 기준: 9명

##### 결측치를 다른 값으로 대체
```fillna()``` 메서드
- **기본 문법**: `df['컬럼'].fillna(값)`
- **주요 파라미터**:
  - `value`: 대체할 값
  - `inplace=True`: 원본 데이터 직접 수정

**주요 메서드**
  - `ffill (Forward Fill)`: **앞(위)에** 있는 정상적인 값으로 채움
  - `bfill (Backward Fill)`: **뒤(아래)에** 있는 정상적인 값으로 채움

⚠️ 주의사항
  첫번째/마지막행이 결측치인데 ffill/bfill을 쓰면 가져올 값이 없으므로 여전히 결측치로 남음.

In [ ]:
# 결측치 처리용 데이터 복사
df_filled = df_patients.copy()

df_filled.head()

  PatientID   Age   BMI  BloodPressure  Diabetes  Income
0      P001  25.0  22.5          120.0       0.0    50.0
1      P002  34.0   NaN          130.0       1.0    60.0
2      P003   NaN  28.3          125.0       0.0    45.0
3      P004  45.0  31.2            NaN       NaN    70.0
4      P005  52.0  24.8          140.0       1.0     NaN

In [ ]:
# 방법 1: 고정값으로 대체
df_filled['BMI'] = df_filled['BMI'].fillna(value=0)
print("BMI 결측치를 0으로 대체:")
print(df_filled['BMI'].isnull().sum(), "개 남음")

df_filled[["PatientID", "BMI"]]

BMI 결측치를 0으로 대체:
0 개 남음

  PatientID   BMI
0      P001  22.5
1      P002   0.0
2      P003  28.3
3      P004  31.2
4      P005  24.8
5      P006  29.1
6      P007   0.0
7      P008  21.3
8      P009  26.7
9      P010  33.4

In [ ]:
# 방법 2: 평균값으로 대체
age_mean = df_filled['Age'].mean()
df_filled['Age'] = df_filled['Age'].fillna(age_mean)
print(f"\nAge 결측치를 평균값({age_mean:.1f})으로 대체:")
print(f"기존 결측치: {df_patients['Age'].isnull().sum()}개 -> 현재 결측치: {df_filled['Age'].isnull().sum()}개")

df_filled[["PatientID", "Age"]].round(1)

Age 결측치를 평균값(43.1)으로 대체:
기존 결측치: 2개 -> 현재 결측치: 0개

  PatientID   Age
0      P001  25.0
1      P002  34.0
2      P003  43.1
3      P004  45.0
4      P005  52.0
5      P006  43.1
6      P007  67.0
7      P008  23.0
8      P009  41.0
9      P010  58.0

In [ ]:
# 방법 3: 중앙값으로 대체
income_median = df_filled['Income'].median()
df_filled['Income'] = df_filled['Income'].fillna(income_median)
print(f"BMI 결측치를 중앙값({income_median:.1f})으로 대체:")
print(f"기존 결측치: {df_patients['Income'].isnull().sum()}개 -> 현재 결측치: {df_filled['Income'].isnull().sum()}개")

df_filled[["PatientID", "Income"]]

BMI 결측치를 중앙값(57.5)으로 대체:
기존 결측치: 2개 -> 현재 결측치: 0개

  PatientID  Income
0      P001    50.0
1      P002    60.0
2      P003    45.0
3      P004    70.0
4      P005    57.5
5      P006    55.0
6      P007    80.0
7      P008    40.0
8      P009    65.0
9      P010    57.5

In [ ]:
# 방법 4: 앞 값으로 채우기
df_filled['BloodPressure'] = df_filled['BloodPressure'].ffill()
print(f"\nBloodPressure 앞 값으로 채우기:")

df_filled[['PatientID', 'BloodPressure']]   # P004, P009

BloodPressure 앞 값으로 채우기:

  PatientID  BloodPressure
0      P001          120.0
1      P002          130.0
2      P003          125.0
3      P004          125.0
4      P005          140.0
5      P006          135.0
6      P007          150.0
7      P008          118.0
8      P009          118.0
9      P010          160.0

In [ ]:
print(f"\n최종 결측치 현황:")
print(df_filled.isnull().sum())

최종 결측치 현황:
PatientID        0
Age              0
BMI              0
BloodPressure    0
Diabetes         1
Income           0
dtype: int64

**의료 데이터 결측치 처리 가이드라인**
- 나이, 성별: 삭제 금지 (핵심 정보)
- 혈압, BMI: 평균값 대체 적절
- 진단 여부: 최빈값 or 별도 카테고리

### 🤔 실습 문제: 환자 생체지표 결측치 처리

**문제**: 결측치를 적절한 방법으로 처리하세요.

1. **나이**: 평균값으로 대체
2. **BMI**: 중앙값으로 대체  
3. **혈당**: 고정값 100으로 대체

**힌트**:
- 평균값 대체: `df['컬럼'].fillna(df['컬럼'].mean())`
- 중앙값 대체: `df['컬럼'].fillna(df['컬럼'].median())`
- 고정값 대체: `df['컬럼'].fillna(값)`

In [ ]:
# 건강검진 환자 데이터
checkup_data = {
    'PatientID': ['H001', 'H002', 'H003', 'H004', 'H005', 'H006', 'H007', 'H008'],  # 환자 고유 번호
    'Age': [35, 42, None, 28, 55, 67, None, 45],  # 나이 (세)
    'BMI': [23.5, None, 28.1, 22.0, None, 31.8, 26.5, 29.2],  # 체질량지수 (kg/m²)
    'BloodSugar': [95, 110, 88, None, 140, None, 102, 125],  # 공복혈당 (mg/dL)
}
df_checkup = pd.DataFrame(checkup_data)  # 딕셔너리를 DataFrame으로 변환
df_checkup = pd.DataFrame(checkup_data)

df_checkup

  PatientID   Age   BMI  BloodSugar
0      H001  35.0  23.5        95.0
1      H002  42.0   NaN       110.0
2      H003   NaN  28.1        88.0
3      H004  28.0  22.0         NaN
4      H005  55.0   NaN       140.0
5      H006  67.0  31.8         NaN
6      H007   NaN  26.5       102.0
7      H008  45.0  29.2       125.0

In [ ]:
# 여기에 작성하세요

# 1. 나이를 평균값으로 대체

# 2. BMI를 중앙값으로 대체

# 3. 혈당을 100으로 대체

# 처리 결과 확인
print("결측치 처리 후:")
print(df_checkup.isnull().sum())   # 모든 행 0으로 만들기

결측치 처리 후:
PatientID     0
Age           2
BMI           2
BloodSugar    2
dtype: int64

In [ ]:
# @title 정답

# 건강검진 환자 데이터
checkup_data = {
    'PatientID': ['H001', 'H002', 'H003', 'H004', 'H005', 'H006', 'H007', 'H008'],  # 환자 고유 번호
    'Age': [35, 42, None, 28, 55, 67, None, 45],  # 나이 (세)
    'BMI': [23.5, None, 28.1, 22.0, None, 31.8, 26.5, 29.2],  # 체질량지수 (kg/m²)
    'BloodSugar': [95, 110, 88, None, 140, None, 102, 125],  # 공복혈당 (mg/dL)
}
df_checkup = pd.DataFrame(df_checkup)

# 1. 나이를 평균값으로 대체
df_checkup['Age'] = df_checkup['Age'].fillna(df_checkup['Age'].mean())

# 2. BMI를 중앙값으로 대체
df_checkup['BMI'] = df_checkup['BMI'].fillna(df_checkup['BMI'].median())

# 3. 혈당을 100으로 대체
df_checkup['BloodSugar'] = df_checkup['BloodSugar'].fillna(100)

# 처리 결과 확인
print("결측치 처리 후:")
print(df_checkup.isnull().sum())


df_checkup

결측치 처리 후:
PatientID     0
Age           0
BMI           0
BloodSugar    0
dtype: int64

  PatientID        Age   BMI  BloodSugar
0      H001  35.000000  23.5        95.0
1      H002  42.000000  27.3       110.0
2      H003  45.333333  28.1        88.0
3      H004  28.000000  22.0       100.0
4      H005  55.000000  27.3       140.0
5      H006  67.000000  31.8       100.0
6      H007  45.333333  26.5       102.0
7      H008  45.000000  29.2       125.0

### 중복 데이터 탐지 및 제거

#### 중복 데이터란?

중복 데이터(Duplicate Data)는 동일한 정보가 여러 번 기록된 데이터를 의미합니다.

**중복 데이터가 AI 모델링에 미치는 문제**  
중복된 데이터는 AI 모델이 특정 환자나 케이스에 과도하게 편향되어 학습하게 만듭니다. 이로 인해 일반화 성능이 떨어지고, 실제 환경에서 정확도가 크게 감소할 수 있습니다.

**예를 들어** 같은 환자의 검사 결과가 실수로 3번 입력된 경우, AI 모델은 이 환자의 특성을 3배 중요하게 학습하게 되어 유사한 다른 환자들에 대해 잘못된 진단을 내릴 가능성이 높아집니다.

#### 중복 데이터 확인하기

In [ ]:
# 중복 데이터 샘플
duplicate_data = {
    'PatientID': ['P001', 'P002', 'P003', 'P001', 'P004', 'P002'],    # 'P001', 'P002' 중복
    'Name': ['김철수', '이영희', '박민수', '김철수2', '최지은', '이영희2'],
    'Age': [45, 32, 28, 45, 55, 32],
    'BMI': [25.3, 22.1, 28.7, 25.3, 31.2, 22.1]
}

df_duplicates = pd.DataFrame(duplicate_data)
print("중복이 포함된 환자 데이터:")

df_duplicates

중복이 포함된 환자 데이터:

  PatientID  Name  Age   BMI
0      P001   김철수   45  25.3
1      P002   이영희   32  22.1
2      P003   박민수   28  28.7
3      P001  김철수2   45  25.3
4      P004   최지은   55  31.2
5      P002  이영희2   32  22.1

#### 중복 데이터 탐지 방법
**duplicated() - 중복 행 탐지**
- **기능**: 중복된 행을 True/False로 표시 (첫 번째는 False, 나머지는 True)
- **주요 파라미터**: `subset=['컬럼명']` (특정 컬럼 기준)

In [ ]:
# 중복 확인
is_duplicate = df_duplicates.duplicated(subset=['PatientID'])  # PatientID 기준
print(f"중복 환자: {is_duplicate.sum()}명")

# 중복된 환자 확인
duplicate_patients = df_duplicates[is_duplicate]
print("중복된 환자 목록:")

duplicate_patients[['PatientID', 'Name']]

중복 환자: 2명
중복된 환자 목록:

  PatientID  Name
3      P001  김철수2
5      P002  이영희2

#### 중복 데이터 처리 방법
**drop_duplicates() - 중복 행 제거**  
- **기능**: 중복 행을 삭제한 새로운 DataFrame 반환
- **keep 옵션**:
  - `'first'`: 첫 번째로 나타난 행 유지 (기본값)
  - `'last'`: 마지막으로 나타난 행 유지 (최신 정보 유지에 유용)
- **실무 활용**: 환자ID 기준으로 최신 정보만 유지

In [ ]:
# 중복 제거 (최신 정보 유지)
df_unique_patients = df_duplicates.drop_duplicates(subset=['PatientID'], keep='last')

print(f"중복 제거 결과:")
print(f"원본: {len(df_duplicates)}명 → 처리 후: {len(df_unique_patients)}명")

df_unique_patients[['PatientID', 'Name', 'Age']]

중복 제거 결과:
원본: 6명 → 처리 후: 4명

  PatientID  Name  Age
2      P003   박민수   28
3      P001  김철수2   45
4      P004   최지은   55
5      P002  이영희2   32

### 이상치 탐지 및 처리

#### 이상치란?

이상치(Outliers)는 다른 데이터들과 현저하게 다른 값을 가진 관측치입니다.

**이상치가 AI 모델링에 미치는 문제**  
이상치는 AI 모델의 학습을 왜곡시켜 대부분의 정상적인 환자들보다 극단적인 케이스에 맞춰 예측하게 만듭니다. 특히 선형 모델에서는 이상치 하나가 전체 예측선을 크게 변경시킬 수 있습니다.

**예를 들어** BMI가 200인 데이터 입력 오류(실제로는 20.0)가 있으면, AI는 비만과 당뇨병의 관계를 과도하게 학습하여 정상 체중 환자에게도 당뇨병 고위험군으로 잘못 분류할 수 있습니다.

**⚠️ 이상한 값 vs 특별한 값**  
BMI 100, 혈압 300처럼 의학적으로 불가능한 값은 오류이지만,  
극단적이지만 가능한 값(BMI 50, 나이 100세)은 실제 환자일 수 있습니다.

그러므로, **입력 오류(Error)인지**, **실제 극단적인 케이스(Severity)인지** 구분하는 것이 중요합니다.

- 입력 오류 (Data Error) → 삭제 (Drop)
- 임상적 극단값 (Clinical Extreme) → 조정 (Capping/Winsorizing)

In [ ]:
# BMI 데이터 (88.5는 의도적 이상치)
bmi_data = [18.5, 22.1, 25.3, 28.7, 31.2, 19.8, 24.5, 27.3, 35.6, 88.5, 21.7, 26.1, 29.4]   # 13 개
bmi_series = pd.Series(bmi_data, name='BMI')

print("원본 BMI 데이터:")
bmi_series.head()

원본 BMI 데이터:

0    18.5
1    22.1
2    25.3
3    28.7
4    31.2
Name: BMI, dtype: float64

#### IQR 방법으로 이상치 탐지

**IQR (Interquartile Range) 방법**
- **원리**: 1사분위수(Q1)와 3사분위수(Q3) 사이의 범위를 이용
- **이상치 기준**: Q1 - 1.5 × IQR 미만 또는 Q3 + 1.5 × IQR 초과
  - 정규분포에서 ```Q1 - 1.5 × IQR``` ~ ```Q3 + 1.5 × IQR``` 범위는 약 99.3%의 데이터를 포함
  - 즉, 0.7%만 이상치로 분류 → 적절한 민감도
- **장점**: 분포에 관계없이 사용 가능, 이해하기 쉬움

In [ ]:
# 사분위수 계산
Q1 = bmi_series.quantile(0.25)  # 하위 25% 지점
Q3 = bmi_series.quantile(0.75)  # 상위 25% 지점
IQR = Q3 - Q1                   # 중간 50% 범위

print(f"\nBox Plot 기준값:")
print(f"Q1: {Q1:.1f}, Q3: {Q3:.1f}, IQR: {IQR:.1f}")

Box Plot 기준값:
Q1: 22.1, Q3: 29.4, IQR: 7.3

In [ ]:
# 이상치 경계선 계산 (Box Plot의 수염 끝)
lower_bound = Q1 - 1.5 * IQR  # 하한선
upper_bound = Q3 + 1.5 * IQR  # 상한선

print(f"정상 범위: {lower_bound:.1f} ~ {upper_bound:.1f}")

정상 범위: 11.2 ~ 40.3

In [ ]:
# 이상치 탐지 및 분류
outliers_condition = (bmi_series < lower_bound) | (bmi_series > upper_bound)   # 불린 Series 반환, 조건에 부합하면 True
outliers = bmi_series[outliers_condition]  # 이상치만 추출
normal_values = bmi_series[~outliers_condition]  # 정상값만 추출

print(f"\n통계적 이상치: {outliers.values} ({len(outliers)}개)")
print(f"정상 범위값: {normal_values.values} ({len(normal_values)}개)")

통계적 이상치: [88.5] (1개)
정상 범위값: [18.5 22.1 25.3 28.7 31.2 19.8 24.5 27.3 35.6 21.7 26.1 29.4] (12개)

### 🤔 실습 문제: 혈압 데이터 이상치 분석

**문제**: IQR 방법으로 이상치를 탐지하세요.

1. **Q1, Q3, IQR 계산**
2. **이상치 경계선 계산** (Q1-1.5×IQR, Q3+1.5×IQR)  
3. **이상치 환자 탐지 및 출력**

**힌트**:
- 사분위수: `df['컬럼'].quantile(0.25)`, `df['컬럼'].quantile(0.75)`
- 조건 필터링: `df[df['컬럼'] > 값]`

In [ ]:
# 고혈압 클리닉 환자 혈압 데이터
df_patients = {
    'PatientID': ['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P009', 'P010'],  # 환자 ID
    'SystolicBP': [118, 125, 132, 140, 350, 135, 142, 138, 50, 147]  # 수축기 혈압 (mmHg) - 350과 50은 의도적 이상치
}
df_bp = pd.DataFrame(df_patients)

df_bp.head()

  PatientID  SystolicBP
0      P001         118
1      P002         125
2      P003         132
3      P004         140
4      P005         350

In [ ]:
# 여기에 작성하세요

# 1. 사분위수 계산

# 2. 이상치 경계선 계산

# 3. 이상치 환자 탐지 및 출력

In [ ]:
# @title 정답

# 고혈압 클리닉 환자 혈압 데이터
df_patients = {
    'PatientID': ['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P009', 'P010'],  # 환자 ID
    'SystolicBP': [118, 125, 132, 140, 350, 135, 142, 138, 50, 147]  # 수축기 혈압 (mmHg) - 350과 50은 의도적 이상치
}
df_bp = pd.DataFrame(df_patients)

# 1. 사분위수 계산
Q1 = df_bp['SystolicBP'].quantile(0.25)
Q3 = df_bp['SystolicBP'].quantile(0.75)
IQR = Q3 - Q1

print(f"Q1: {Q1:.1f}, Q3: {Q3:.1f}, IQR: {IQR:.1f}")

# 2. 이상치 경계선 계산
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"정상 범위: {lower_bound:.1f} ~ {upper_bound:.1f}")

# 3. 이상치 환자 탐지 및 출력
outlier_patients = df_bp[(df_bp['SystolicBP'] < lower_bound) | (df_bp['SystolicBP'] > upper_bound)]
normal_patients = df_bp[(df_bp['SystolicBP'] >= lower_bound) & (df_bp['SystolicBP'] <= upper_bound)]

print(f"\n이상치 환자:")
print(outlier_patients[['PatientID', 'SystolicBP']])

print(f"\n정상 범위 환자:")
print(normal_patients[['PatientID', 'SystolicBP']])

Q1: 126.8, Q3: 141.5, IQR: 14.8
정상 범위: 104.6 ~ 163.6

이상치 환자:
  PatientID  SystolicBP
4      P005         350
8      P009          50

정상 범위 환자:
  PatientID  SystolicBP
0      P001         118
1      P002         125
2      P003         132
3      P004         140
5      P006         135
6      P007         142
7      P008         138
9      P010         147

### 데이터 타입 확인 및 변환

#### 데이터 타입 문제란?

데이터 타입 문제는 데이터가 AI가 처리할 수 없는 잘못된 형태로 저장된 경우를 의미합니다.

**데이터 타입 문제가 AI 모델링에 미치는 영향**  
숫자 데이터가 문자열로 저장되어 있으면 AI 모델이 수학적 연산(평균, 표준편차 등)을 수행할 수 없어 학습이 불가능합니다.   

**예를 들어** 환자의 나이가 '25세'로 문자열 저장된 경우, AI는 나이와 질병 위험도 간의 수치적 관계를 학습할 수 없어 연령별 맞춤 진단이 불가능해집니다.

In [ ]:
# 타입 문제가 있는 데이터
type_issue_data = {
    'PatientID': ['P001', 'P002', 'P003', 'P004', 'P005'],
    'Age': ['25', '34', '45', '52', '67'],  # 문자로 저장된 나이
    'BMI': ['22.5', '28.3', 'NULL', '24.8', '31.2'],  # 문자와 NULL 섞임
    'Date': ['2024-01-15', '2024-02-20', '2024-03-10', '2024-04-05', '2024-05-12'],
    'Income': [50000, 60000, 45000, 47000, 80000]
}

df_types = pd.DataFrame(type_issue_data)
print("타입 문제가 있는 데이터:")

df_types

타입 문제가 있는 데이터:

  PatientID Age   BMI        Date  Income
0      P001  25  22.5  2024-01-15   50000
1      P002  34  28.3  2024-02-20   60000
2      P003  45  NULL  2024-03-10   45000
3      P004  52  24.8  2024-04-05   47000
4      P005  67  31.2  2024-05-12   80000

In [ ]:
print(f"\n데이터 타입 확인:")
print(df_types.dtypes)    # 문자열은 object로 표시됨

print(f"\n데이터 정보:")
print(df_types.info())

데이터 타입 확인:
PatientID    object
Age          object
BMI          object
Date         object
Income        int64
dtype: object

데이터 정보:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PatientID  5 non-null      object
 1   Age        5 non-null      object
 2   BMI        5 non-null      object
 3   Date       5 non-null      object
 4   Income     5 non-null      int64
dtypes: int64(1), object(4)
memory usage: 332.0+ bytes
None

#### 데이터 타입 변환

**1. astype() - 강제 타입 변환**
- **기능**: 지정한 데이터 타입으로 강제 변환
- **주의**: 변환 불가능한 값이 있으면 오류 발생
- **활용**: 확실히 변환 가능한 경우에 사용

In [ ]:
# 문자열 나이를 숫자로 변환
df_types['Age_numeric'] = df_types['Age'].astype(int)   # 변환하여 컬럼 추가
print(f"Age 타입: {df_types['Age'].dtype} → {df_types['Age_numeric'].dtype}")
print(f"변환 결과: {df_types['Age'].values} → {df_types['Age_numeric'].values}")

Age 타입: object → int64
변환 결과: ['25' '34' '45' '52' '67'] → [25 34 45 52 67]

In [ ]:
# 'Null'과 혼재되어있는 BMI를 숫자로 변환 ('Null'은 숫자로 변환 불가!)
df_types['BMI_numeric'] = df_types['BMI'].astype(int)   # 변환하여 컬럼 추가
print(f"BMI 타입: {df_types['BMI'].dtype} → {df_types['BMI_numeric'].dtype}")
print(f"변환 결과: {df_types['BMI'].values} → {df_types['BMI_numeric'].values}")

ValueError: invalid literal for int() with base 10: '22.5'

**2. pd.to_numeric() & pd.to_datetime() - 안전한 변환**
- **to_numeric**: 문자열을 숫자로 안전하게 변환
- **to_datetime**: 문자열을 날짜로 변환
- **errors='coerce'**: 변환 불가능한 값은 NaN으로 처리 강제

In [ ]:
# 안전한 숫자 변환 (오류값은 NaN으로)
df_types['BMI_numeric'] = pd.to_numeric(df_types['BMI'], errors='coerce')
print(f"BMI 변환: {df_types['BMI'].values} → {df_types['BMI_numeric'].values}")

BMI 변환: ['22.5' '28.3' 'NULL' '24.8' '31.2'] → [22.5 28.3  nan 24.8 31.2]

In [ ]:
# 날짜 변환 및 정보 추출
print(f"Date 데이터 타입: {df_types['Date'].dtype}")

df_types['Date_datetime'] = pd.to_datetime(df_types['Date'])

print(f"Date_datetime 데이터 타입: {df_types['Date_datetime'].dtype}")

Date 데이터 타입: object
Date_datetime 데이터 타입: datetime64[ns]

In [ ]:
# 연도, 월, 일 별로 변환
df_types['Year'] = df_types['Date_datetime'].dt.year
df_types['Month'] = df_types['Date_datetime'].dt.month
df_types['Day'] = df_types['Date_datetime'].dt.day

print(f"날짜 변환: {df_types['Date'].values[0]} → {df_types['Year'].values[0]}")
print(f"날짜 변환: {df_types['Date'].values[0]} → {df_types['Month'].values[0]}")
print(f"날짜 변환: {df_types['Date'].values[0]} → {df_types['Day'].values[0]}")

날짜 변환: 2024-01-15 → 2024
날짜 변환: 2024-01-15 → 1
날짜 변환: 2024-01-15 → 15

In [ ]:
df_types.loc[:, "Date_datetime":]

  Date_datetime  Year  Month  Day
0    2024-01-15  2024      1   15
1    2024-02-20  2024      2   20
2    2024-03-10  2024      3   10
3    2024-04-05  2024      4    5
4    2024-05-12  2024      5   12

In [ ]:
# 변환으로 생긴 결측치 확인
print(f"변환 후 결측치: {df_types['BMI_numeric'].isnull().sum()}개")   # nan

변환 후 결측치: 1개