# 💡 SQL vs. SQLAlchemy Core 메서드 매핑

| SQL 구문                 | SQLAlchemy Core 메서드              | 설명                                        |
| :----------------------- | :---------------------------------- | :------------------------------------------ |
| `CREATE DATABASE`        | `engine.execute("CREATE DATABASE")` | 데이터베이스 생성                            |
| `CREATE TABLE`           | `Table(...)`, `metadata.create_all(engine)` | 테이블 구조 정의 및 실제 테이블 생성         |
| `INSERT INTO ... VALUES` | `table.insert()`, `conn.execute(...)` | 테이블에 데이터 추가                         |
| `SELECT ... FROM ...`    | `select(...)`                       | 테이블에서 데이터 조회                       |
| `WHERE 조건`             | `.where(...)`                       | 특정 조건을 만족하는 데이터 필터링           |
| `ORDER BY 컬럼`          | `.order_by(...)`                    | 특정 컬럼 기준으로 데이터 정렬               |
| `LIMIT 숫자`             | `.limit(...)`                       | 조회 결과의 개수 제한                        |
| `COUNT(컬럼)`            | `func.count(table.c.column)`        | 특정 컬럼의 개수 세기 (집계 함수)            |
| `AVG(컬럼)`              | `func.avg(table.c.column)`          | 특정 컬럼의 평균 계산 (집계 함수)            |
| `GROUP BY 컬럼`          | `.group_by(...)`                    | 특정 컬럼 기준으로 데이터를 그룹화           |
| `HAVING 조건`            | `.having(...)`                      | 그룹화된 결과에 조건 필터링                  |
| `AS 별칭`                | `.label('별칭')`                    | 컬럼이나 집계 결과에 별명 지정               |
| `JOIN`                   | `.join(...)`                        | 여러 테이블을 연결하여 데이터 조회           |
| `UPDATE ... SET ... WHERE` | `update(...)`, `.where(...)`, `.values(...)` | 테이블의 특정 데이터 수정                    |
| `DELETE FROM ... WHERE`  | `delete(...)`, `.where(...)`        | 테이블에서 특정 데이터 삭제                  |
| `COMMIT`                 | `conn.commit()`                     | 데이터베이스 변경사항 최종 반영 (필수!!!)      |

# 1. 🏗️ 기본 세팅

환경 설정을 위해 아래 코드를 실행해주세요. MySQL 서버 설치 및 라이브러리 로드가 진행됩니다.

In [ ]:
from IPython.core.magics import display
from 개인.practice import result
# # 1. MySQL 서버 설치 및 실행
# !apt-get update
# !apt-get install mysql-server > /dev/null
# !service mysql start

# # 2. 보안 설정 변경 (비밀번호 없이 접속 허용)
# !mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
#
# # 3. 라이브러리 설치 및 SQL 확장 로드
# !pip install ipython-sql pymysql sqlalchemy
%load_ext sql

# 4. 접속 및 에러 방지 설정
%sql mysql+pymysql://root:1234@localhost/
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

# 2. 📝 데이터 준비: 마음 건강 상담 센터 시스템

### 🧠 심리 상담 데이터 설계

상담 센터에서 사용하는 **내담자 관리 및 상담 일지** 데이터를 설계해봅시다.

1. **내담자 테이블 (`clients`)**: 상담을 받는 사람 (이름, 나이, 주요 고민 키워드)
2. **상담사 테이블 (`counselors`)**: 센터 전문가 (이름, 전공 분야, 경력 연수)
3. **상담 기록 (`sessions`)**: 개별 상담 정보 (내담자ID, 상담사ID, 상담 만족도, 상담 시간)

이 데이터를 통해 '상담사별 평균 만족도'나 '연령대별 주요 고민' 등을 분석할 수 있습니다.

In [14]:
import pandas as pd
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Float, DateTime, ForeignKey, select, func, update, delete, text
from datetime import datetime

# 1. 엔진 설정: 상담센터 데이터베이스(counsel_db) 생성
engine = create_engine('mysql+pymysql://root:1234@localhost/')

with engine.connect() as conn:
    conn.execute(text("CREATE DATABASE IF NOT EXISTS counsel_db"))
    conn.commit()

engine = create_engine('mysql+pymysql://root:1234@localhost/counsel_db')
metadata = MetaData()

# 내담자 테이블
clients = Table('clients', metadata,
    Column('id', Integer, primary_key=True),
    Column('name', String(50), nullable=False),
    Column('age', Integer),
    Column('concern', String(50)) # 대인관계, 진로, 우울 등
)

# 상담사 테이블
counselors = Table('counselors', metadata,
    Column('id', Integer, primary_key=True),
    Column('name', String(50), nullable=False),
    Column('major', String(50)) # 아동심리, 성인상담 등
)

# 상담 기록 테이블
sessions = Table('sessions', metadata,
    Column('id', Integer, primary_key=True),
    Column('client_id', Integer, ForeignKey('clients.id')),
    Column('counselor_id', Integer, ForeignKey('counselors.id')),
    Column('satisfaction', Integer), # 1~5점
    Column('session_date', DateTime, default=datetime.now)
)

metadata.create_all(engine)

# 데이터 적재
with engine.connect() as conn:
    # 기존 데이터 삭제 (중복 방지)
    conn.execute(sessions.delete())
    conn.execute(clients.delete())
    conn.execute(counselors.delete())

    conn.execute(clients.insert(), [
        {'id': 1, 'name': '이민지', 'age': 24, 'concern': '취업준비'},
        {'id': 2, 'name': '정태양', 'age': 35, 'concern': '직장스트레스'},
        {'id': 3, 'name': '최하늘', 'age': 18, 'concern': '학업'},
        {'id': 4, 'name': '홍길동', 'age': 20, 'concern': '대인관계'}
    ])
    conn.execute(counselors.insert(), [
        {'id': 1, 'name': '김지혜', 'major': '성인상담'},
        {'id': 2, 'name': '박성진', 'major': '청소년상담'}
    ])
    conn.execute(sessions.insert(), [
        {'client_id': 1, 'counselor_id': 1, 'satisfaction': 5},
        {'client_id': 2, 'counselor_id': 1, 'satisfaction': 4},
        {'client_id': 3, 'counselor_id': 2, 'satisfaction': 5}
    ])
    conn.commit()

print("🧠 마음 건강 상담 센터 데이터베이스 구축 완료!")

🧠 마음 건강 상담 센터 데이터베이스 구축 완료!

# 3. 📝 연습하기

## 📊 데이터 조회하기

데이터베이스에서 정보를 가져오는 가장 기본적인 작업은 `SELECT` 문입니다. SQLAlchemy Core에서는 `select()` 함수를 사용하여 이를 수행합니다.

`select(patients)`: `patients` 테이블의 모든 컬럼을 선택하라는 의미입니다. SQL의 `SELECT * FROM patients` 와 같습니다.

### 조건 필터링 (WHERE)

`where()` 메서드는 SQL의 `WHERE` 절과 동일하게 특정 조건을 만족하는 행(레코드)만 선택할 때 사용합니다.

`patients.c.age >= 30`: `patients` 테이블의 `age` 컬럼 값이 30 이상인 조건을 나타냅니다. `.c`는 '컬럼(column)'을 의미하며, `patients.c.age`는 `patients` 테이블의 `age` 컬럼을 지칭합니다.

In [16]:
stmt = select(clients).where(clients.c.age >= 20)
with engine.connect() as coon:
    result = coon.execute(stmt)
    print(result.fetchall())

[(1, '이민지', 24, '취업준비'), (2, '정태양', 35, '직장스트레스'), (4, '홍길동', 20, '대인관계')]

### 결과 정렬 (ORDER BY)

`order_by()` 메서드는 SQL의 `ORDER BY` 절처럼 조회된 결과를 특정 컬럼을 기준으로 정렬할 때 사용합니다.

`patients.c.age.desc()`: `patients` 테이블의 `age` 컬럼을 기준으로 내림차순(descending)으로 정렬하라는 의미입니다. 오름차순은 `.asc()`를 사용하거나 생략합니다.

In [29]:
# 여기에 코드를 입력하세요
stmt = select(clients).order_by(clients.c.age.desc())
with engine.connect() as conn:
    result = conn.execute(stmt)
    display(pd.DataFrame(result.fetchall(), columns = result.keys()))

   id name  age concern
0   2  정태양   35  직장스트레스
1   1  이민지   24    취업준비
2   4  홍길동   20    대인관계
3   3  최하늘   18      학업

F### 결과 개수 제한 (LIMIT)

`limit()` 메서드는 SQL의 `LIMIT` 절처럼 조회 결과의 개수를 제한할 때 사용합니다. 주로 상위 N개의 데이터를 확인할 때 유용합니다.

`limit(2)`: 조회된 결과 중 상위 2개의 행만 반환하라는 의미입니다.

In [ ]:
# 여기에 코드를 입력하세요

## 📈 데이터 집계 (COUNT, AVG, GROUP BY, HAVING)

데이터 집계는 여러 데이터를 그룹으로 묶어 합계, 평균, 개수 등을 계산하여 의미 있는 통계를 얻는 작업입니다. SQLAlchemy Core에서는 `func` 객체와 `group_by()`, `having()` 메서드를 활용합니다.

### 집계 함수 (COUNT, AVG)

`func` 객체는 `COUNT()`, `AVG()`, `SUM()`, `MAX()`, `MIN()` 등 다양한 SQL 집계 함수들을 파이썬에서 사용할 수 있게 해줍니다.

*   `func.count(patients.c.id)`: `patients` 테이블의 `id` 컬럼의 개수를 세라는 의미입니다. 각 그룹에 속한 데이터의 수를 알 수 있습니다.
*   `func.avg(patients.c.age)`: `patients` 테이블의 `age` 컬럼의 평균값을 계산하라는 의미입니다.

In [40]:
stmt = select(
    func.count(sessions.c.id).label("상담 횟수"),
    func.avg(sessions.c.satisfaction).label("평균 만족도")
)
with engine.connect() as conn:
    result = conn.execute(stmt)
    print(result.fetchall())

[(3, Decimal('4.6667'))]

### 별칭 지정 (LABEL/AS)

`label('별칭')` 메서드는 SQL의 `AS` 키워드처럼 컬럼이나 계산된 결과에 읽기 쉬운 별명(Alias)을 붙일 때 사용합니다.

*   `func.count(patients.c.id).label('인원수')`: `count(id)` 결과를 `인원수`라는 이름으로 표시합니다.

In [ ]:
# 여기에 코드를 입력하세요

### 그룹화 (GROUP BY)

`group_by()` 메서드는 SQL의 `GROUP BY` 절처럼 특정 컬럼의 동일한 값을 기준으로 데이터를 그룹으로 묶습니다. 집계 함수는 이 그룹별로 실행됩니다.

*   `group_by(patients.c.gender)`: `patients` 테이블의 `gender` (성별) 컬럼을 기준으로 데이터를 그룹화합니다. 예를 들어 'M' 그룹과 'F' 그룹으로 나뉩니다.

In [37]:
# 여기에 코드를 입력하세요
stmt = select(
    clients.c.concern,
    func.count(clients.c.id).label('concern'),
).group_by(clients.c.concern)
with engine.connect() as conn:
    result = conn.execute(stmt)
    print(result.fetchall())

[('취업준비', 1), ('직장스트레스', 1), ('학업', 1), ('대인관계', 1)]

### 그룹 필터링 (HAVING)

`having()` 메서드는 `group_by()`로 그룹화된 결과에 대해 조건을 필터링할 때 사용합니다. `WHERE` 절이 개별 행에 조건을 적용한다면, `HAVING` 절은 그룹 전체에 조건을 적용합니다.

*   `having(func.avg(patients.c.age) >= 30)`: 그룹별로 계산된 `age`의 평균값이 30 이상인 그룹만 선택하라는 의미입니다.

In [42]:
# 여기에 코드를 입력하세요
stmt = select(
    sessions.c.counselor_id,
    func.count(sessions.c.id).label('상담횟수')
).group_by(sessions.c.counselor_id).having(func.count(sessions.c.id) >= 2)
with engine.connect() as conn:
    result = conn.execute(stmt)
    display(pd.DataFrame(result.fetchall(), columns = result.keys()))

   counselor_id  상담횟수
0             1     2

## 🔗 데이터 조인(Join)

`JOIN`은 여러 테이블에 흩어져 있는 관련 데이터를 하나로 합쳐서 조회할 때 사용되는 매우 중요한 기능입니다. 예를 들어 환자 정보, 의사 정보, 예약 정보가 각각 다른 테이블에 있을 때, 누가 어떤 의사에게 언제 예약했는지 한 번에 보려면 이 테이블들을 연결해야 합니다. SQLAlchemy Core에서는 `join()` 메서드를 사용합니다.

### `select_from()`과 `join()`

*   **`select_from()`**: 어떤 테이블에서부터 조인을 시작할지 명시적으로 지정합니다.
*   **`join(다른_테이블, 조인_조건)`**: 기본적으로 **INNER JOIN**을 수행하며, 두 테이블에 모두 데이터가 존재할 때만 결과를 가져옵니다.
*   **`isouter=True`**: `join()` 내에 이 옵션을 추가하면 **LEFT JOIN**이 되어, 왼쪽 테이블(시작 테이블)의 모든 데이터를 유지하고 오른쪽 테이블에 정보가 없으면 `NULL`로 표시합니다.

In [47]:
# 여기에 코드를 입력하세요
stmt = select(
    clients.c.name.label('성함'),
    sessions.c.satisfaction.label('만족도')
).select_from(
    clients.join(
        sessions,
        clients.c.id == sessions.c.client_id
    )
)

with engine.connect() as conn:
    result = conn.execute(stmt)
    display(pd.DataFrame(result.fetchall(),columns=result.keys()))

    성함  만족도
0  이민지    5
1  정태양    4
2  최하늘    5

## 🛠️ 데이터 수정 및 삭제

데이터베이스에 저장된 데이터를 변경하거나 더 이상 필요 없는 데이터를 지우는 것은 중요한 관리 작업입니다. SQLAlchemy Core에서는 `update()`와 `delete()` 함수를 사용하여 이 작업을 안전하게 수행할 수 있습니다.

### 변경사항 반영 (`conn.commit()`)

`update()`나 `delete()` 같은 데이터 변경(DML: Data Manipulation Language) 작업은 `conn.execute()`로 실행한 후, 반드시 `conn.commit()`을 호출해야 데이터베이스에 최종적으로 변경사항이 반영됩니다. `commit()`을 하지 않으면 변경사항은 임시 상태로만 존재하다가 연결이 끊기면 사라질 수 있습니다. 이는 데이터의 일관성과 무결성을 보장하기 위한 중요한 절차입니다.

In [49]:
from sqlalchemy import insert

stmt = insert(clients).values(
    name='정현우',
    age=20,
    concern='연애'
)
with engine.connect() as conn:
    conn.execute(stmt)
    conn.commit()

### 데이터 수정 (UPDATE)

`update(테이블).where(조건).values(수정할_값)`

*   `update(patients)`: `patients` 테이블의 데이터를 수정하겠다는 의미입니다.
*   `.where(patients.c.name == '박민수')`: `name` 컬럼의 값이 '박민수'인 행(레코드)만 수정하라는 조건입니다. `WHERE` 절을 사용하지 않으면 테이블의 모든 데이터가 수정되므로 주의해야 합니다!
*   `.values(age=46)`: 선택된 행의 `age` 컬럼 값을 46으로 변경하라는 의미입니다. 여러 컬럼을 동시에 수정할 수도 있습니다 (예: `values(age=46, gender='M')`).

SQL 문으로 표현하면 `UPDATE patients SET age = 46 WHERE name = '박민수';` 와 같습니다.

In [56]:
# 여기에 코드를 입력하세요
stmt = update(clients).where(clients.c.id==1).values(concern='연애')

with engine.connect() as conn:
    conn.execute(stmt)
    conn.commit()
    result=conn.execute(select(clients))
    print(result.fetchall())

[(1, '이민지', 24, '연애'), (2, '정태양', 35, '직장스트레스'), (4, '홍길동', 20, '대인관계'), (6, '정현우', 20, '연애')]

### 데이터 삭제 (DELETE)

`delete(테이블).where(조건)`

*   `delete(patients)`: `patients` 테이블의 데이터를 삭제하겠다는 의미입니다.
*   `.where(patients.c.id == 3)`: `id` 컬럼의 값이 3인 행(레코드)만 삭제하라는 조건입니다. 마찬가지로 `WHERE` 절을 사용하지 않으면 테이블의 모든 데이터가 삭제되므로 **극도로 주의해야 합니다!**

SQL 문으로 표현하면 `DELETE FROM patients WHERE id = 3;` 와 같습니다.

In [55]:
# 여기에 코드를 입력하세요
stmt_1 = delete(sessions).where(sessions.c.client_id == 3)
stmt_2 = delete(clients).where(clients.c.id==3)
with engine.connect() as conn:
    conn.execute(stmt_1)
    conn.execute(stmt_2)
    result = conn.execute(select(clients))
    conn.commit()
    print(result.fetchall())

[(1, '이민지', 24, '연애'), (2, '정태양', 35, '직장스트레스'), (4, '홍길동', 20, '대인관계'), (6, '정현우', 20, '연애')]

# 4. 🚀 심화 분석: 데이터 성능과 안전성 확보하기

기본적인 조회와 수정을 넘어, 실무에서 데이터베이스의 성능을 최적화하고 예기치 못한 에러로부터 데이터를 안전하게 보호하는 고급 기법을 배워봅시다.

### ⚡ 데이터 찾기 속도 높이기: 인덱스(Index)

데이터가 수만, 수백만 건이 넘어가면 특정 조건(예: 이름으로 조회)으로 데이터를 찾는 속도가 느려집니다. 이때 특정 컬럼에 **인덱스(Index)** 를 설정하면 마치 책의 '찾아보기'처럼 데이터를 훨씬 빠르게 찾을 수 있습니다.

* **장점**: `SELECT` 조회 성능이 비약적으로 향상됩니다.
* **단점**: 데이터를 넣거나(`INSERT`) 수정할 때(`UPDATE`) 인덱스도 함께 업데이트해야 하므로 속도가 조금 느려질 수 있고, 추가적인 저장 공간이 필요합니다.

In [57]:
from sqlalchemy import Index

name_index = Index("ix_client_name",clients.c.name)
name_index.create(bind=engine)

with engine.connect() as conn:
    result = conn.execute(text("SHOW INDEX FROM clients"))
    display(pd.DataFrame(result.fetchall(),columns=result.keys()))

,Table,Non_unique,Key_name,Seq_in_index,Column_name,Collation,Cardinality,Sub_part,Packed,Null,Index_type,Comment,Index_comment,Visible,Expression
0,clients,0,PRIMARY,1,id,A,4,None,None,,BTREE,,,YES,None
1,clients,1,ix_client_name,1,name,A,4,None,None,,BTREE,,,YES,None

### 🛡️ 데이터 일관성 지키기: 예외 처리 (Error Handling)

데이터베이스 작업 중에는 중복된 ID를 입력하거나, 필수 값이 빠지는 등 다양한 에러가 발생할 수 있습니다. 프로그램이 갑자기 멈추지 않도록 `try-except` 문을 사용해 에러를 처리할 수 있습니다.

In [ ]:
# 여기에 코드를 입력하세요

### 🛡️ 데이터의 안전장치: 트랜잭션(Transaction)

여러 단계를 하나의 묶음으로 처리해야 할 때 사용합니다. 모든 단계가 성공해야만 최종 반영(`commit`)하고, 중간에 하나라도 실패하면 모든 작업을 취소(`rollback`)하여 데이터의 일관성을 지킵니다.

In [ ]:
# 여기에 코드를 입력하세요

with engine.connect() as conn:
    try:
    except Exception e:
        conn.rollback()
        print("에러발생")