# 🏗️ 기본 세팅

## MongoDB 서버 및 Python 패키지 설치

In [ ]:
# # 1. MongoDB 공식 GPG 키 및 리포지토리 등록
# !curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
# !echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
#
# # 2. 패키지 목록 업데이트 및 설치
# !apt-get update
# !apt-get install -y mongodb-org > /dev/null
#
# # 3. MongoDB 서비스 실행
# !mkdir -p /data/db
# !mongod --fork --logpath /var/log/mongodb.log --dbpath /data/db
#
# # 4. 파이썬용 드라이버 설치
# !pip install pymongo

## MongoDB 접속 정보 넣기

In [1]:
import os
from pymongo import MongoClient
from bson import json_util  # $oid, $numberInt 등을 처리하기 위해 필수!

# 1. 로컬 MongoDB 연결
client = MongoClient('mongodb://localhost:27017/')
db = client.sample_mflix
movies = db.movies

# 2. 데이터 다운로드 (Raw 주소)
url = "https://raw.githubusercontent.com/neelabalan/mongodb-sample-dataset/main/sample_mflix/movies.json"
print("데이터 다운로드 중...")
os.system(f"wget -q -O movies.json {url}")

# 3. 데이터 파싱 및 DB 삽입
if os.path.exists('movies.json'):
    with open('movies.json', 'r') as f:
        try:
            # json_util을 사용하여 $oid 등의 특수 형식을 변환하며 읽기
            data = [json_util.loads(line) for line in f if line.strip()]

            # 중복 삽입 방지 및 데이터 주입
            if movies.count_documents({}) == 0:
                movies.insert_many(data)
                print(f"✅ 로드 성공! 총 {movies.count_documents({})}개의 문서가 저장되었습니다.")
            else:
                print(f"ℹ️ 이미 {movies.count_documents({})}개의 데이터가 DB에 있습니다.")
        except Exception as e:
            print(f"❌ 데이터 처리 중 오류 발생: {e}")
else:
    print("❌ movies.json 파일을 찾을 수 없습니다.")

# 4. 확인용 쿼리
sample = movies.find_one()
if sample:
    print(f"\n🔍 확인용 데이터:")
    print(f"제목: {sample.get('title')}")
    print(f"ID타입: {type(sample.get('_id'))}") # <class 'bson.objectid.ObjectId'> 로 나옴

데이터 다운로드 중...
✅ 로드 성공! 총 23539개의 문서가 저장되었습니다.

🔍 확인용 데이터:
제목: Blacksmith Scene
ID타입: <class 'bson.objectid.ObjectId'>

# 📝 연습하기

## 컬렉션 사용 준비

`sample_mflix` 데이터베이스의 `movies` 컬렉션은 이미 준비되어 있습니다.

삽입, 업데이트, 삭제와 같은 연습을 위해 `temp_movies`라는 임시 컬렉션을 생성하여 사용할 예정이며, 컬렉션은 첫 도큐먼트가 삽입될 때 자동으로 생성됩니다.

In [2]:
# 여기에 코드를 입력하세요.
temp_collection = db.temp_movies
print("완료")

완료

## 도큐먼트 삽입

### `insert_one()`: 단일 도큐먼트 삽입

`insert_one()` 메서드를 사용하여 컬렉션에 하나의 도큐먼트를 삽입합니다. 삽입된 도큐먼트의 `_id`를 반환받을 수 있습니다.

In [4]:
# 여기에 코드를 입력하세요.

test_mv= {
    "title":"OZ AH05",
    "year":"2026",
    "genre":["Comedy","Action"]
}
temp_collection.insert_one(test_mv)

InsertOneResult(ObjectId('69e9b033a83931b7031f0266'), acknowledged=True)

### `insert_many()`: 여러 도큐먼트 삽입

`insert_many()` 메서드를 사용하여 여러 도큐먼트를 리스트 형태로 한 번에 삽입합니다. 삽입된 모든 도큐먼트의 `_id` 리스트를 반환받을 수 있습니다.

In [5]:
# 여기에 코드를 입력하세요.
test_mv= [
    {
        "title":"OZ AH01",
        "year":"2025",
        "genre":["Comedy","Romance"]
    },
    {
        "title":"OZ AH02",
        "year":"2024",
        "genre":["Comedy","Horror"]
    },
    {
        "title":"OZ AH03",
        "year":"2023",
        "genre":["Fantasy","Action"]
    },
    {
        "title":"OZ AH04",
        "year":"2022",
        "genre":["comedy","Action"]
    },
]
temp_collection.insert_many(test_mv)

InsertManyResult([ObjectId('69e9b24ea83931b7031f0267'), ObjectId('69e9b24ea83931b7031f0268'), ObjectId('69e9b24ea83931b7031f0269'), ObjectId('69e9b24ea83931b7031f026a')], acknowledged=True)

## 데이터 조회

### `find_one()`: 조건에 맞는 첫 번째 도큐먼트 조회

`find_one()` 메서드는 주어진 조건과 일치하는 첫 번째 도큐먼트를 반환합니다. 조건이 없으면 컬렉션의 첫 번째 도큐먼트를 반환합니다.

In [11]:
# 여기에 코드를 입력하세요.
import pandas as pd
result = temp_collection.find_one({"title":"OZ AH05"})
display(pd.DataFrame([result]))

                        _id    title  year             genre
0  69e9b033a83931b7031f0266  OZ AH05  2026  [Comedy, Action]

### `find()`: 조건에 맞는 모든 도큐먼트 조회

`find()` 메서드는 주어진 조건과 일치하는 모든 도큐먼트를 반환하는 커서(cursor) 객체를 반환합니다. 커서를 반복하여 도큐먼트들을 하나씩 접근할 수 있습니다.

In [25]:
# 여기에 코드를 입력하세요.
result = list(movies.find({'year':1920}))
display(pd.DataFrame(result))

,_id,plot,genres,runtime,rated,cast,num_mflix_comments,poster,title,fullplot,...,released,directors,writers,awards,lastupdated,year,imdb,countries,type,tomatoes
0,573a1391f29313caabcd6d40,A tipsy doctor encounters his patient sleepwal...,"[Comedy, Short]",26,PASSED,"[Harold Lloyd, Roy Brooks, Mildred Davis, Wall...",3.0,https://m.media-amazon.com/images/M/MV5BODliMj...,High and Dizzy,"After a long wait, a young doctor finally has ...",...,1920-07-11,[Hal Roach],"[Frank Terry (story), H.M. Walker (titles)]","{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-08-11 00:35:33.717000000,1920,"{'rating': 7, 'votes': 646, 'id': 11293}",[USA],movie,"{'viewer': {'rating': 3.4, 'numReviews': 30, '..."
1,573a1391f29313caabcd6d90,As Alice and Cora Munro attempt to find their ...,"[Adventure, Drama]",73,NOT RATED,"[Wallace Beery, Barbara Bedford, Alan Roscoe, ...",NaN,https://m.media-amazon.com/images/M/MV5BZmJkZD...,The Last of the Mohicans,As Alice and Cora Munro attempt to find their ...,...,1920-11-21,"[Clarence Brown, Maurice Tourneur]","[James Fenimore Cooper (novel), Robert Dillon ...","{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-07-19 00:12:27.010000000,1920,"{'rating': 6.9, 'votes': 773, 'id': 11387}",[USA],movie,"{'viewer': {'rating': 3.5, 'numReviews': 306, ..."
2,573a1391f29313caabcd6e2a,A newly wedded couple attempt to build a house...,"[Short, Comedy]",25,TV-G,"[Buster Keaton, Sybil Seely]",1.0,NaN,One Week,Buster and Sybil exit a chapel as newlyweds. A...,...,1920-09-01,"[Edward F. Cline, Buster Keaton]",NaN,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-05-07 01:07:01.633000000,1920,"{'rating': 8.3, 'votes': 3942, 'id': 11541}",[USA],movie,"{'viewer': {'rating': 4.3, 'numReviews': 752, ..."
3,573a1391f29313caabcd6ea2,The simple-minded son of a rich financier must...,[Comedy],77,NaN,"[Edward Jobson, Beulah Booker, Edward Connelly...",2.0,https://m.media-amazon.com/images/M/MV5BZDNiOD...,The Saphead,Nick Van Alstyne owns the Henrietta silver min...,...,1920-09-01,"[Herbert Blachè, Winchell Smith]","[Bronson Howard (original play ""The Henrietta""...","{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-06-20 00:38:08.303000000,1920,"{'rating': 6.2, 'votes': 1020, 'id': 11652}",[USA],movie,"{'viewer': {'rating': 3.3, 'numReviews': 435, ..."
4,573a1391f29313caabcd6f8f,"Abandoned by her fiancè, an educated negro wom...","[Drama, Romance]",79,NaN,"[Evelyn Preer, Flo Clements, James D. Ruffin, ...",NaN,NaN,Within Our Gates,Southern negro Sylvia Landry visits her cousin...,...,1920-01-12,[Oscar Micheaux],[Oscar Micheaux],"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-21 00:15:06.017000000,1920,"{'rating': 6.3, 'votes': 1138, 'id': 11870}",[USA],movie,"{'viewer': {'rating': 3.4, 'numReviews': 391, ..."
5,573a139ff29313caabd01709,NaN,[Western],80,NaN,"[Em-koy-e-tie, Hunting Horse, Esther LeBarre, ...",NaN,NaN,The Daughter of Dawn,NaN,...,1920-10-01,[Norbert A. Myles],"[Richard Banks (story), Norbert A. Myles]","{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-09-03 00:33:47.333000000,1920,"{'rating': 6.4, 'votes': 30, 'id': 191066}",[USA],movie,"{'viewer': {'rating': 0, 'numReviews': 2}, 'la..."

## Projection (프로젝션)

프로젝션은 `find()` 또는 `find_one()` 메서드 사용 시 결과 도큐먼트에서 원하는 필드만 선택하여 가져오는 기능입니다.

두 번째 인자로 딕셔너리를 전달하여 필드를 포함하거나 제외할 수 있습니다.
`_id` 필드를 제외하려면 `_id: 0`으로 설정하면 됩니다.

In [29]:
# 여기에 코드를 입력하세요.
result = movies.find({'year':1920},{'runtime':1,'rated':1,'title':1,'_id':0})
for doc in result:
    display(pd.DataFrame([doc]))

   runtime   rated           title
0       26  PASSED  High and Dizzy

   runtime      rated                     title
0       73  NOT RATED  The Last of the Mohicans

   runtime     title rated
0       25  One Week  TV-G

   runtime        title
0       77  The Saphead

   runtime             title
0       79  Within Our Gates

   runtime                 title
0       80  The Daughter of Dawn

## `sort()` & `limit()`

### `sort()`: 결과 정렬

`sort()` 메서드는 조회 결과를 특정 필드를 기준으로 정렬.
`1`: 오름차순 / `-1`: 내림차순

### `limit()`: 결과 개수 제한

`limit()` 메서드는 조회 결과의 최대 개수를 제한함.

In [32]:
# 여기에 코드를 입력하세요.
result = movies.find({},{"title":1,"_id":0,"year":1}).sort("year",-1).limit(10)
display(pd.DataFrame(result))

                                 title   year
0                        The Saboteurs  2015è
1                      Halo: Nightfall  2014è
2  The Roosevelts: An Intimate History  2014è
3                           Hit & Miss  2012è
4                              Penance  2012è
5             The Weight of the Nation  2012è
6                        Vietnam in HD  2011è
7                        Falling Skies  2011è
8           Stephen Hawking's Universe  2010è
9         Third Reich: The Rise & Fall  2010è

## 도큐먼트 업데이트

### `update_one()`: 단일 도큐먼트 업데이트

`update_one()` 메서드는 주어진 조건과 일치하는 첫 번째 도큐먼트를 업데이트합니다.

`$set` 연산자를 사용하여 필드를 설정할 수 있습니다.

In [39]:
# 여기에 코드를 입력하세요.
pre = movies.find_one({"title":"The Ace of Hearts"},{"hah":1,"year":1,"title":1,"_id":0})
print(pre)
print("수정전")
result = movies.update_one(
    {"title":"The Ace of Hearts"},
    {
        "$set":{"hah":"skrRR"}
    }
)
print("2021 -> 2020 수정완료")
print(f"매치된 도큐먼트 수: {result.matched_count}")
print(f"수정된 도큐먼트 수: {result.modified_count}")
print("수정후")
post = movies.find_one({"title":"The Ace of Hearts"},{"hah":1,"year":1,"title":1,"_id":0})
display(post)

{'title': 'The Ace of Hearts', 'year': 2020}
수정전
2021 -> 2020 수정완료
매치된 도큐먼트 수: 1
수정된 도큐먼트 수: 1
수정후

{'title': 'The Ace of Hearts', 'year': 2020, 'hah': 'skrRR'}

### `update_many()`: 여러 도큐먼트 업데이트

`update_many()` 메서드는 주어진 조건과 일치하는 모든 도큐먼트를 업데이트합니다.

In [ ]:
# 여기에 코드를 입력하세요.
result = movies.update_many(
    {"title":"The Ace of Hearts"},
    {
    "$set":{"hah":"skrRR"}
    }
)

## 도큐먼트 삭제

### `delete_one()`: 단일 도큐먼트 삭제

`delete_one()` 메서드는 주어진 조건과 일치하는 첫 번째 도큐먼트를 삭제합니다.

In [40]:
# 여기에 코드를 입력하세요.
result = movies.delete_one({"title":"The Ace of Hearts"})
print(f"삭제된 doc수{result.deleted_count}")

삭제된 doc수1

0

## 컬렉션 삭제

### `drop()`: 컬렉션 전체 삭제

`drop()` 메서드는 컬렉션 자체를 완전히 삭제합니다. 이 작업은 되돌릴 수 없으므로 주의해야 합니다.

In [41]:
temp_collection.drop()
print('temp_movies'in db.list_collection_names())

False

## Aggregation

`Aggregation Pipeline`

여러 단계(stage)를 순차적으로 거치면서 데이터를 변환하고 분석하는 MongoDB의 강력한 기능입니다.
SQL의 GROUP BY, HAVING, ORDER BY, 데이터 전처리 기능을 합친 것과 비슷합니다.

### `$match`
`$match` 단계는 조건에 맞는 도큐먼트만 다음 단계로 전달합니다.
SQL의 WHERE 절과 비슷하며, 필터링 시 가장 먼저 사용하는 단계입니다.

$match는 MongoDB의 다양한 비교 연산자를 함께 사용할 수 있습니다.

- `$eq`  : 같다 (=)

- `$gte`: 크거나 같다 (>=)

- `$lte`: 작거나 같다 (<=)

- `$gt` : 크다 (>)

- `$lt` : 작다 (<)

- `$ne` : 같지 않다 (!=)

- `$in` : 여러 값 중 일치하는 것 조회

- `$nin` : 배열 안에 없는 경우

In [47]:
# 여기에 코드를 입력하세요.
res_1 = movies.aggregate([
    {
        "$match":{
            "year":{"$gte":2001},
            "imdb.rating":{"$gt":7}
        }
    },
    {
        "$limit":5
    }
])
display(list(res_1))

[{'_id': ObjectId('573a139af29313caabcf0ea6'),
  'fullplot': '"Frida" chronicles the life Frida Kahlo shared unflinchingly and openly with Diego Rivera, as the young couple took the art world by storm. From her complex and enduring relationship with her mentor and husband to her illicit and controversial affair with Leon Trotsky, to her provocative and romantic entanglements with women, Frida Kahlo lived a bold and uncompromising life as a political, artistic, and sexual revolutionary.',
  'imdb': {'rating': 7.4, 'votes': 57256, 'id': 120679},
  'year': 2002,
  'plot': 'A biography of artist Frida Kahlo, who channeled the pain of a crippling injury and her tempestuous marriage into her work.',
  'genres': ['Biography', 'Drama', 'Romance'],
  'rated': 'R',
  'metacritic': 61,
  'title': 'Frida',
  'lastupdated': '2015-09-12 00:33:36.510000000',
  'languages': ['English', 'French', 'Russian'],
  'writers': ['Hayden Herrera (book)',
   'Clancy Sigal (screenplay)',
   'Diane Lake (screenplay)',
   'Gregory Nava (screenplay)',
   'Anna Thomas (screenplay)'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.miramax.com/frida/',
   'viewer': {'rating': 3.7, 'numReviews': 53261, 'meter': 86},
   'dvd': datetime.datetime(2003, 6, 10, 0, 0),
   'critic': {'rating': 6.9, 'numReviews': 151, 'meter': 76},
   'boxOffice': '$25.7M',
   'consensus': 'Frida is a passionate, visually striking biopic about the larger-than-life artist.',
   'rotten': 36,
   'production': 'Miramax Films',
   'lastUpdated': datetime.datetime(2015, 9, 13, 18, 8, 34),
   'fresh': 115},
  'poster': 'https://m.media-amazon.com/images/M/MV5BYzUxMTU0ZmEtZWE0Ni00NzJlLThhZTUtNDA1ZDZjZDUxYThiXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 2,
  'released': datetime.datetime(2002, 11, 22, 0, 0),
  'awards': {'wins': 19,
   'nominations': 33,
   'text': 'Won 2 Oscars. Another 17 wins & 33 nominations.'},
  'countries': ['USA', 'Canada', 'Mexico'],
  'cast': ['Salma Hayek', 'Mèa Maestro', 'Alfred Molina', 'Antonio Banderas'],
  'directors': ['Julie Taymor'],
  'runtime': 123},
 {'_id': ObjectId('573a139af29313caabcf0f07'),
  'fullplot': 'An ancient Ring thought lost for centuries has been found, and through a strange twist in fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it! However he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir and his three Hobbit friends Merry, Pippin and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign!',
  'imdb': {'rating': 8.8, 'votes': 1109724, 'id': 120737},
  'year': 2001,
  'plot': 'A meek hobbit of the Shire and eight companions set out on a journey to Mount Doom to destroy the One Ring and the dark lord Sauron.',
  'genres': ['Adventure', 'Fantasy'],
  'rated': 'PG-13',
  'metacritic': 92,
  'title': 'The Lord of the Rings: The Fellowship of the Ring',
  'lastupdated': '2015-08-31 00:05:39.967000000',
  'languages': ['English', 'Sindarin'],
  'writers': ['J.R.R. Tolkien (novel)',
   'Fran Walsh (screenplay)',
   'Philippa Boyens (screenplay)',
   'Peter Jackson (screenplay)'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.lordoftherings.net/film/trilogy/thefellowship.html',
   'viewer': {'rating': 4.1, 'numReviews': 1348869, 'meter': 95},
   'dvd': datetime.datetime(2002, 8, 6, 0, 0),
   'critic': {'rating': 8.2, 'numReviews': 225, 'meter': 91},
   'boxOffice': '$313.8M',
   'consensus': "Full of eye-popping special effects, and featuring a pitch-perfect cast, The Lord of the Rings: The Fellowship of the Ring brings J.R.R. Tolkien's classic to vivid life.",
   'rotten': 20,
   'production': 'New Line Cinema',
   'lastUpdated': datetime.datetime(2015, 9, 12, 17, 56, 50),
   'fresh': 205},
  'poster': 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 381,
  'released': datetime.datetime(2001, 12, 19, 0, 0),
  'awards': {'wins': 114,
   'nominations': 100,
   'text': 'Won 4 Oscars. Another 110 wins & 100 nominations.'},
  'countries': ['New Zealand', 'USA'],
  'cast': ['Alan Howard', 'Noel Appleby', 'Sean Astin', 'Sala Baker'],
  'directors': ['Peter Jackson'],
  'runtime': 178},
 {'_id': ObjectId('573a139af29313caabcf1044'),
  'fullplot': "Set back in the late 1800s in a Victorian village, a man and woman by the names of Victor Van Dort and Victoria Everglot are betrothed because the Everglots need the money or else they'll be living on the streets and the Van Dorts want to be hight in society. But when things go wrong at the wedding rehearsal, Victor goes into the woods to practice his vows. Just as soon as he gets them right, he finds himself married to Emily, the corpse bride. While Victoria waits on the other side, there's a rich newcomer that may take Victor's place. So two brides, one groom, who will Victor pick?",
  'imdb': {'rating': 7.4, 'votes': 170384, 'id': 121164},
  'year': 2005,
  'plot': 'When a shy groom practices his wedding vows in the inadvertent presence of a deceased young woman, she rises from the grave assuming he has married her.',
  'genres': ['Animation', 'Fantasy', 'Musical'],
  'rated': 'PG',
  'metacritic': 83,
  'title': 'Corpse Bride',
  'lastupdated': '2015-09-05 00:50:50.993000000',
  'languages': ['English'],
  'writers': ['Tim Burton (characters)',
   'Carlos Grangel (characters)',
   'John August (screenplay)',
   'Caroline Thompson (screenplay)',
   'Pamela Pettler (screenplay)'],
  'type': 'movie',
  'tomatoes': {'website': 'http://corpsebridemovie.warnerbros.com/',
   'viewer': {'rating': 3.5, 'numReviews': 551130, 'meter': 77},
   'dvd': datetime.datetime(2006, 1, 31, 0, 0),
   'critic': {'rating': 7.2, 'numReviews': 187, 'meter': 83},
   'boxOffice': '$53.3M',
   'consensus': 'As can be expected from a Tim Burton movie, Corpse Bride is whimsically macabre, visually imaginative, and emotionally bittersweet.',
   'rotten': 31,
   'production': 'Warner Bros. Pictures',
   'lastUpdated': datetime.datetime(2015, 9, 12, 17, 41, 19),
   'fresh': 156},
  'poster': 'https://m.media-amazon.com/images/M/MV5BMTk1MTY1NjU4MF5BMl5BanBnXkFtZTcwNjIzMTEzMw@@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 3,
  'released': datetime.datetime(2005, 9, 23, 0, 0),
  'awards': {'wins': 12,
   'nominations': 19,
   'text': 'Nominated for 1 Oscar. Another 11 wins & 19 nominations.'},
  'countries': ['UK', 'USA'],
  'cast': ['Johnny Depp',
   'Helena Bonham Carter',
   'Emily Watson',
   'Tracey Ullman'],
  'directors': ['Tim Burton', 'Mike Johnson'],
  'runtime': 77},
 {'_id': ObjectId('573a139af29313caabcf124d'),
  'fullplot': "Three years after the onset of the Clone Wars; the noble Jedi Knights are spread out across the galaxy leading a massive clone army in the war against the Separatists. After Chancellor Palpatine is kidnapped, Jedi Master Obi-Wan Kenobi and his former Padawan, Anakin Skywalker, are dispatched to eliminate the evil General Grievous. Meanwhile, Anakin's friendship with the Chancellor arouses suspicion in the Jedi Order, and dangerous to the Jedi Knight himself. When the sinister Sith Lord, Darth Sidious, unveils a plot to take over the galaxy, the fate of Anakin, the Jedi order, and the entire galaxy is at stake. Upon his return, Anakin Skywalker's wife Padme Amidala is pregnant, but he is having visions of her dying in childbirth. Anakin Skywalker ultimately turns his back on the Jedi, thus completing his journey to the dark side and his transformation into Darth Vader. Obi-Wan Kenobi must face his former apprentice in a ferocious lightsaber duel on the fiery world of Mustafar.",
  'imdb': {'rating': 7.7, 'votes': 440441, 'id': 121766},
  'year': 2005,
  'plot': 'As the Clone Wars near an end, the Sith Lord Darth Sidious steps out of the shadows, at which time Anakin succumbs to his emotions, becoming Darth Vader and putting his relationships with Obi-Wan and Padme at risk.',
  'genres': ['Action', 'Adventure', 'Fantasy'],
  'rated': 'PG-13',
  'metacritic': 68,
  'title': 'Star Wars: Episode III - Revenge of the Sith',
  'lastupdated': '2015-09-07 00:05:05.403000000',
  'languages': ['English'],
  'writers': ['George Lucas'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.starwars.com/',
   'viewer': {'rating': 3.1, 'numReviews': 33671923, 'meter': 65},
   'dvd': datetime.datetime(2005, 11, 1, 0, 0),
   'critic': {'rating': 7.2, 'numReviews': 253, 'meter': 80},
   'boxOffice': '$380.2M',
   'consensus': "This sixth and final installment of George Lucas' epic space opera will please die-hard fanatics and non-believers alike -- largely due to awesome digital effects and the sheer power of the mythology.",
   'rotten': 51,
   'production': '20th Century Fox',
   'lastUpdated': datetime.datetime(2015, 9, 12, 17, 4, 2),
   'fresh': 202},
  'poster': 'https://m.media-amazon.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 424,
  'released': datetime.datetime(2005, 5, 19, 0, 0),
  'awards': {'wins': 19,
   'nominations': 38,
   'text': 'Nominated for 1 Oscar. Another 18 wins & 38 nominations.'},
  'countries': ['USA'],
  'cast': ['Ewan McGregor',
   'Natalie Portman',
   'Hayden Christensen',
   'Ian McDiarmid'],
  'directors': ['George Lucas'],
  'runtime': 140},
 {'_id': ObjectId('573a139af29313caabcf224e'),
  'fullplot': "When a green ogre named Shrek discovers his swamp has been 'swamped' with all sorts of fairytale creatures by the scheming Lord Farquaad, Shrek sets out with a very loud donkey by his side to 'persuade' Farquaad to give Shrek his swamp back. Instead, a deal is made. Farquaad, who wants to become the King, sends Shrek to rescue Princess Fiona, who is awaiting her true love in a tower guarded by a fire-breathing dragon. But once they head back with Fiona, it starts to become apparent that not only does Shrek, an ugly ogre, begin to fall in love with the lovely princess, but Fiona is also hiding a huge secret.",
  'imdb': {'rating': 7.9, 'votes': 420957, 'id': 126029},
  'year': 2001,
  'plot': 'After his swamp is filled with magical creatures, an ogre agrees to rescue a princess for a villainous lord in order to get his land back.',
  'genres': ['Animation', 'Adventure', 'Comedy'],
  'rated': 'PG',
  'metacritic': 84,
  'title': 'Shrek',
  'lastupdated': '2015-08-31 00:06:08.810000000',
  'languages': ['English'],
  'writers': ['William Steig (book)',
   'Ted Elliott (screenplay)',
   'Terry Rossio (screenplay)',
   'Joe Stillman (screenplay)',
   'Roger S.H. Schulman (screenplay)',
   'Cody Cameron (additional dialogue)',
   'Chris Miller (additional dialogue)',
   'Conrad Vernon (additional dialogue)'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.shrek.com/',
   'viewer': {'rating': 3.9, 'numReviews': 1375608, 'meter': 90},
   'dvd': datetime.datetime(2001, 11, 2, 0, 0),
   'critic': {'rating': 7.8, 'numReviews': 200, 'meter': 88},
   'boxOffice': '$267.0M',
   'consensus': "While simultaneously embracing and subverting fairy tales, the irreverent Shrek also manages to tweak Disney's nose, provide a moral message to children, and offer viewers a funny, fast-paced ride.",
   'rotten': 24,
   'production': 'Dreamworks',
   'lastUpdated': datetime.datetime(2015, 9, 12, 18, 15, 48),
   'fresh': 176},
  'poster': 'https://m.media-amazon.com/images/M/MV5BOGZhM2FhNTItODAzNi00YjA0LWEyN2UtNjJlYWQzYzU1MDg5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 375,
  'released': datetime.datetime(2001, 5, 18, 0, 0),
  'awards': {'wins': 37,
   'nominations': 51,
   'text': 'Won 1 Oscar. Another 36 wins & 51 nominations.'},
  'countries': ['USA'],
  'cast': ['Mike Myers', 'Eddie Murphy', 'Cameron Diaz', 'John Lithgow'],
  'directors': ['Andrew Adamson', 'Vicky Jenson'],
  'runtime': 90}]

In [49]:
res_2 = movies.aggregate([
    {
        "$match":{
            "year":{"$gte":2000,"$lte":2009},
            "imdb.rating":{"$gt":7},
            "genres":{"$in":["Mystery"]}
        }
    },
    {"$limit":5}
])
display(list(res_2))

[{'_id': ObjectId('573a139ef29313caabcfbc36'),
  'plot': 'After a car wreck on the winding Mulholland Drive renders a woman amnesiac, she and a perky Hollywood-hopeful search for clues and answers across Los Angeles in a twisting venture beyond dreams and reality.',
  'genres': ['Drama', 'Mystery', 'Thriller'],
  'runtime': 147,
  'metacritic': 81,
  'rated': 'R',
  'cast': ['Naomi Watts', 'Jeanne Bates', 'Dan Birnbaum', 'Laura Harring'],
  'poster': 'https://m.media-amazon.com/images/M/MV5BNWM2MDZmMDgtYjViOS00YzBmLWE4YzctMDMyYTQ2YTc4MmVkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SY1000_SX677_AL_.jpg',
  'title': 'Mulholland Drive',
  'fullplot': 'A bright-eyed young actress travels to Hollywood, only to be ensnared in a dark conspiracy involving a woman who was nearly murdered, and now has amnesia because of a car crash. Eventually, both women are pulled into a psychotic illusion involving a dangerous blue box, a director named Adam Kesher, and the mysterious night club Silencio.',
  'languages': ['English', 'Spanish'],
  'released': datetime.datetime(2001, 10, 19, 0, 0),
  'directors': ['David Lynch'],
  'writers': ['David Lynch'],
  'awards': {'wins': 50,
   'nominations': 40,
   'text': 'Nominated for 1 Oscar. Another 49 wins & 40 nominations.'},
  'lastupdated': '2015-09-02 00:15:58.163000000',
  'year': 2001,
  'imdb': {'rating': 8, 'votes': 217268, 'id': 166924},
  'countries': ['France', 'USA'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.mulholland-drive.com',
   'viewer': {'rating': 3.7, 'numReviews': 186038, 'meter': 88},
   'dvd': datetime.datetime(2002, 4, 9, 0, 0),
   'critic': {'rating': 7.4, 'numReviews': 155, 'meter': 81},
   'boxOffice': '$7.1M',
   'consensus': "David Lynch's dreamlike and mysterious Mulholland Drive is a twisty neo-noir with an unconventional structure that features a mesmirizing performance from Naomi Watts as a woman on the dark fringes of Hollywood.",
   'rotten': 29,
   'production': 'Universal Focus',
   'lastUpdated': datetime.datetime(2015, 9, 12, 17, 50, 4),
   'fresh': 126}},
 {'_id': ObjectId('573a139ff29313caabcff3cf'),
  'fullplot': 'In the year 2054 A.D. crime is virtually eliminated from Washington D.C. thanks to an elite law enforcing squad "Precrime". They use three gifted humans (called "Pre-Cogs") with special powers to see into the future and predict crimes beforehand. John Anderton heads Precrime and believes the system\'s flawlessness steadfastly. However one day the Pre-Cogs predict that Anderton will commit a murder himself in the next 36 hours. Worse, Anderton doesn\'t even know the victim. He decides to get to the mystery\'s core by finding out the \'minority report\' which means the prediction of the female Pre-Cog Agatha that "might" tell a different story and prove Anderton innocent.',
  'imdb': {'rating': 7.7, 'votes': 369160, 'id': 181689},
  'year': 2002,
  'plot': 'In a future where a special police unit is able to arrest murderers before they commit their crimes, an officer from that unit is himself accused of a future murder.',
  'genres': ['Action', 'Mystery', 'Sci-Fi'],
  'rated': 'PG-13',
  'metacritic': 80,
  'title': 'Minority Report',
  'lastupdated': '2015-09-04 00:02:16.007000000',
  'languages': ['English', 'Swedish'],
  'writers': ['Philip K. Dick (short story)',
   'Scott Frank (screenplay)',
   'Jon Cohen (screenplay)'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.minorityreport.com',
   'viewer': {'rating': 3.4, 'numReviews': 478637, 'meter': 80},
   'dvd': datetime.datetime(2002, 12, 17, 0, 0),
   'critic': {'rating': 8.1, 'numReviews': 239, 'meter': 90},
   'boxOffice': '$131.9M',
   'consensus': 'Thought-provoking and visceral, Steven Spielberg successfully combines high concept ideas and high octane action in this fast and febrile sci-fi thriller.',
   'rotten': 23,
   'production': 'Dreamworks',
   'lastUpdated': datetime.datetime(2015, 9, 12, 17, 29, 1),
   'fresh': 216},
  'poster': 'https://m.media-amazon.com/images/M/MV5BZTI3YzZjZjEtMDdjOC00OWVjLTk0YmYtYzI2MGMwZjFiMzBlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 3,
  'released': datetime.datetime(2002, 6, 21, 0, 0),
  'awards': {'wins': 18,
   'nominations': 66,
   'text': 'Nominated for 1 Oscar. Another 17 wins & 66 nominations.'},
  'countries': ['USA'],
  'cast': ['Tom Cruise', 'Max von Sydow', 'Steve Harris', 'Neal McDonough'],
  'directors': ['Steven Spielberg'],
  'runtime': 145},
 {'_id': ObjectId('573a13a0f29313caabd04642'),
  'fullplot': 'Young nurse Sissi lives a secluded life, seemingly entirely devoted to her patients at Birkenhof asylum. Her first encounter with ex-soldier and drifter Bodo has a lasting impact. He causes an accident that results in her lying under a truck, unable to breathe. While he provides life-saving first aid, mesmerized Sissi begins to wonder whether he may be the man of her dreams. But when she tracks him down weeks later her affection is rejected, as Bodo is stuck somewhere between a traumatic past and a criminal future.',
  'imdb': {'rating': 7.6, 'votes': 12753, 'id': 203632},
  'year': 2000,
  'plot': 'Young nurse Sissi lives a secluded life, seemingly entirely devoted to her patients at Birkenhof asylum. Her first encounter with ex-soldier and drifter Bodo has a lasting impact. He causes...',
  'genres': ['Drama', 'Mystery', 'Romance'],
  'rated': 'R',
  'metacritic': 64,
  'title': 'The Princess and the Warrior',
  'lastupdated': '2015-08-08 00:53:36.977000000',
  'languages': ['German'],
  'writers': ['Tom Tykwer'],
  'type': 'movie',
  'tomatoes': {'viewer': {'rating': 2.5, 'numReviews': 2, 'meter': 100},
   'lastUpdated': datetime.datetime(2015, 2, 10, 18, 0, 12)},
  'poster': 'https://m.media-amazon.com/images/M/MV5BMTg0ZDA0NDgtNzlmMy00MTY1LTk1NGUtYjE2MWRkODc2OTZmXkEyXkFqcGdeQXVyMzA3Njg4MzY@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 3,
  'released': datetime.datetime(2000, 10, 12, 0, 0),
  'awards': {'wins': 6, 'nominations': 19, 'text': '6 wins & 19 nominations.'},
  'countries': ['Germany'],
  'cast': ['Franka Potente', 'Benno Fèrmann', 'Joachim Krèl', 'Lars Rudolph'],
  'directors': ['Tom Tykwer'],
  'runtime': 135},
 {'_id': ObjectId('573a13a0f29313caabd05acc'),
  'fullplot': 'Memento chronicles two separate stories of Leonard, an ex-insurance investigator who can no longer build new memories, as he attempts to find the murderer of his wife, which is the last thing he remembers. One story line moves forward in time while the other tells the story backwards revealing more each time.',
  'imdb': {'rating': 8.5, 'votes': 757189, 'id': 209144},
  'year': 2000,
  'plot': 'A man creates a strange system to help him remember things; so he can hunt for the murderer of his wife without his short-term memory loss being an obstacle.',
  'genres': ['Mystery', 'Thriller'],
  'rated': 'R',
  'metacritic': 80,
  'title': 'Memento',
  'lastupdated': '2015-08-23 00:02:21.657000000',
  'languages': ['English'],
  'writers': ['Christopher Nolan (screenplay)',
   'Jonathan Nolan (short story "Memento Mori")'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.otnemem.com',
   'viewer': {'rating': 4.1, 'numReviews': 375899, 'meter': 94},
   'dvd': datetime.datetime(2001, 9, 4, 0, 0),
   'critic': {'rating': 8.2, 'numReviews': 167, 'meter': 92},
   'boxOffice': '$23.8M',
   'consensus': "Christopher Nolan skillfully guides the audience through Memento's fractured narrative, seeping his film in existential dread.",
   'rotten': 13,
   'production': 'Newmarket Films',
   'lastUpdated': datetime.datetime(2015, 9, 12, 17, 21, 21),
   'fresh': 154},
  'poster': 'https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 1,
  'released': datetime.datetime(2001, 5, 25, 0, 0),
  'awards': {'wins': 54,
   'nominations': 44,
   'text': 'Nominated for 2 Oscars. Another 52 wins & 44 nominations.'},
  'countries': ['USA'],
  'cast': ['Guy Pearce',
   'Carrie-Anne Moss',
   'Joe Pantoliano',
   'Mark Boone Junior'],
  'directors': ['Christopher Nolan'],
  'runtime': 113},
 {'_id': ObjectId('573a13a1f29313caabd07754'),
  'fullplot': "On a hot day in a highway gas station men's room, a man Michel doesn't recognize says they went to school together. He's Harry. He suggests they have a drink, so he and his girlfriend follow Michel and his family to their summer place. Michel is amazed when Harry quotes from memory a poem Michel wrote in school. Harry thinks Michel is a great writer, and he's distressed that Michel hasn't written in years. Harry stays awhile (since his father's death, he's a man of leisure) and sets out to eliminate distractions that might keep Michel from writing. First he buys Michel a car (with air conditioning) and then suspicious things happen. Michel picks up a pen, Harry is gratified, but he's not finished being Michel's self-appointed patron.",
  'imdb': {'rating': 7.2, 'votes': 8041, 'id': 216800},
  'year': 2000,
  'plot': "Harry knew Michel in high school; they meet again by accident, Harry inserts himself in Michel's life... and things take a sinister turn.",
  'genres': ['Comedy', 'Drama', 'Mystery'],
  'rated': 'R',
  'metacritic': 75,
  'title': 'With a Friend Like Harry...',
  'lastupdated': '2015-08-18 00:34:00.783000000',
  'languages': ['French', 'Spanish'],
  'writers': ['Dominik Moll (scenario)',
   'Gilles Marchand (scenario)',
   'Francis Villain (poem)'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.diaphana.fr/harry/',
   'viewer': {'rating': 3.6, 'numReviews': 4371, 'meter': 80},
   'dvd': datetime.datetime(2001, 10, 26, 0, 0),
   'critic': {'rating': 7.5, 'numReviews': 90, 'meter': 96},
   'boxOffice': '$3.4M',
   'consensus': "A darkly funny thriller that's reminiscent of Hitchcock.",
   'rotten': 4,
   'production': 'Miramax Films',
   'lastUpdated': datetime.datetime(2015, 9, 15, 18, 25, 44),
   'fresh': 86},
  'poster': 'https://m.media-amazon.com/images/M/MV5BMTgxMTE4MTYzNl5BMl5BanBnXkFtZTYwNTE4OTI5._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 2,
  'released': datetime.datetime(2001, 6, 15, 0, 0),
  'awards': {'wins': 8,
   'nominations': 14,
   'text': 'Nominated for 1 BAFTA Film Award. Another 7 wins & 14 nominations.'},
  'countries': ['France'],
  'cast': ['Laurent Lucas',
   'Sergi Lèpez',
   'Mathilde Seigner',
   'Sophie Guillemin'],
  'directors': ['Dominik Moll'],
  'runtime': 117}]

In [50]:
res_2 = movies.aggregate([
    {
        "$match":{
            "$and":[
                {"year":{"$gte":2000,"$lte":2009}},
                {"imdb.rating":{"$gt":7}},
                {"genres":{"$in":["Mystery"]}}
            ]

        }
    },
    {"$limit":5}
])
display(list(res_2))

[{'_id': ObjectId('573a139ef29313caabcfbc36'),
  'plot': 'After a car wreck on the winding Mulholland Drive renders a woman amnesiac, she and a perky Hollywood-hopeful search for clues and answers across Los Angeles in a twisting venture beyond dreams and reality.',
  'genres': ['Drama', 'Mystery', 'Thriller'],
  'runtime': 147,
  'metacritic': 81,
  'rated': 'R',
  'cast': ['Naomi Watts', 'Jeanne Bates', 'Dan Birnbaum', 'Laura Harring'],
  'poster': 'https://m.media-amazon.com/images/M/MV5BNWM2MDZmMDgtYjViOS00YzBmLWE4YzctMDMyYTQ2YTc4MmVkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SY1000_SX677_AL_.jpg',
  'title': 'Mulholland Drive',
  'fullplot': 'A bright-eyed young actress travels to Hollywood, only to be ensnared in a dark conspiracy involving a woman who was nearly murdered, and now has amnesia because of a car crash. Eventually, both women are pulled into a psychotic illusion involving a dangerous blue box, a director named Adam Kesher, and the mysterious night club Silencio.',
  'languages': ['English', 'Spanish'],
  'released': datetime.datetime(2001, 10, 19, 0, 0),
  'directors': ['David Lynch'],
  'writers': ['David Lynch'],
  'awards': {'wins': 50,
   'nominations': 40,
   'text': 'Nominated for 1 Oscar. Another 49 wins & 40 nominations.'},
  'lastupdated': '2015-09-02 00:15:58.163000000',
  'year': 2001,
  'imdb': {'rating': 8, 'votes': 217268, 'id': 166924},
  'countries': ['France', 'USA'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.mulholland-drive.com',
   'viewer': {'rating': 3.7, 'numReviews': 186038, 'meter': 88},
   'dvd': datetime.datetime(2002, 4, 9, 0, 0),
   'critic': {'rating': 7.4, 'numReviews': 155, 'meter': 81},
   'boxOffice': '$7.1M',
   'consensus': "David Lynch's dreamlike and mysterious Mulholland Drive is a twisty neo-noir with an unconventional structure that features a mesmirizing performance from Naomi Watts as a woman on the dark fringes of Hollywood.",
   'rotten': 29,
   'production': 'Universal Focus',
   'lastUpdated': datetime.datetime(2015, 9, 12, 17, 50, 4),
   'fresh': 126}},
 {'_id': ObjectId('573a139ff29313caabcff3cf'),
  'fullplot': 'In the year 2054 A.D. crime is virtually eliminated from Washington D.C. thanks to an elite law enforcing squad "Precrime". They use three gifted humans (called "Pre-Cogs") with special powers to see into the future and predict crimes beforehand. John Anderton heads Precrime and believes the system\'s flawlessness steadfastly. However one day the Pre-Cogs predict that Anderton will commit a murder himself in the next 36 hours. Worse, Anderton doesn\'t even know the victim. He decides to get to the mystery\'s core by finding out the \'minority report\' which means the prediction of the female Pre-Cog Agatha that "might" tell a different story and prove Anderton innocent.',
  'imdb': {'rating': 7.7, 'votes': 369160, 'id': 181689},
  'year': 2002,
  'plot': 'In a future where a special police unit is able to arrest murderers before they commit their crimes, an officer from that unit is himself accused of a future murder.',
  'genres': ['Action', 'Mystery', 'Sci-Fi'],
  'rated': 'PG-13',
  'metacritic': 80,
  'title': 'Minority Report',
  'lastupdated': '2015-09-04 00:02:16.007000000',
  'languages': ['English', 'Swedish'],
  'writers': ['Philip K. Dick (short story)',
   'Scott Frank (screenplay)',
   'Jon Cohen (screenplay)'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.minorityreport.com',
   'viewer': {'rating': 3.4, 'numReviews': 478637, 'meter': 80},
   'dvd': datetime.datetime(2002, 12, 17, 0, 0),
   'critic': {'rating': 8.1, 'numReviews': 239, 'meter': 90},
   'boxOffice': '$131.9M',
   'consensus': 'Thought-provoking and visceral, Steven Spielberg successfully combines high concept ideas and high octane action in this fast and febrile sci-fi thriller.',
   'rotten': 23,
   'production': 'Dreamworks',
   'lastUpdated': datetime.datetime(2015, 9, 12, 17, 29, 1),
   'fresh': 216},
  'poster': 'https://m.media-amazon.com/images/M/MV5BZTI3YzZjZjEtMDdjOC00OWVjLTk0YmYtYzI2MGMwZjFiMzBlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 3,
  'released': datetime.datetime(2002, 6, 21, 0, 0),
  'awards': {'wins': 18,
   'nominations': 66,
   'text': 'Nominated for 1 Oscar. Another 17 wins & 66 nominations.'},
  'countries': ['USA'],
  'cast': ['Tom Cruise', 'Max von Sydow', 'Steve Harris', 'Neal McDonough'],
  'directors': ['Steven Spielberg'],
  'runtime': 145},
 {'_id': ObjectId('573a13a0f29313caabd04642'),
  'fullplot': 'Young nurse Sissi lives a secluded life, seemingly entirely devoted to her patients at Birkenhof asylum. Her first encounter with ex-soldier and drifter Bodo has a lasting impact. He causes an accident that results in her lying under a truck, unable to breathe. While he provides life-saving first aid, mesmerized Sissi begins to wonder whether he may be the man of her dreams. But when she tracks him down weeks later her affection is rejected, as Bodo is stuck somewhere between a traumatic past and a criminal future.',
  'imdb': {'rating': 7.6, 'votes': 12753, 'id': 203632},
  'year': 2000,
  'plot': 'Young nurse Sissi lives a secluded life, seemingly entirely devoted to her patients at Birkenhof asylum. Her first encounter with ex-soldier and drifter Bodo has a lasting impact. He causes...',
  'genres': ['Drama', 'Mystery', 'Romance'],
  'rated': 'R',
  'metacritic': 64,
  'title': 'The Princess and the Warrior',
  'lastupdated': '2015-08-08 00:53:36.977000000',
  'languages': ['German'],
  'writers': ['Tom Tykwer'],
  'type': 'movie',
  'tomatoes': {'viewer': {'rating': 2.5, 'numReviews': 2, 'meter': 100},
   'lastUpdated': datetime.datetime(2015, 2, 10, 18, 0, 12)},
  'poster': 'https://m.media-amazon.com/images/M/MV5BMTg0ZDA0NDgtNzlmMy00MTY1LTk1NGUtYjE2MWRkODc2OTZmXkEyXkFqcGdeQXVyMzA3Njg4MzY@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 3,
  'released': datetime.datetime(2000, 10, 12, 0, 0),
  'awards': {'wins': 6, 'nominations': 19, 'text': '6 wins & 19 nominations.'},
  'countries': ['Germany'],
  'cast': ['Franka Potente', 'Benno Fèrmann', 'Joachim Krèl', 'Lars Rudolph'],
  'directors': ['Tom Tykwer'],
  'runtime': 135},
 {'_id': ObjectId('573a13a0f29313caabd05acc'),
  'fullplot': 'Memento chronicles two separate stories of Leonard, an ex-insurance investigator who can no longer build new memories, as he attempts to find the murderer of his wife, which is the last thing he remembers. One story line moves forward in time while the other tells the story backwards revealing more each time.',
  'imdb': {'rating': 8.5, 'votes': 757189, 'id': 209144},
  'year': 2000,
  'plot': 'A man creates a strange system to help him remember things; so he can hunt for the murderer of his wife without his short-term memory loss being an obstacle.',
  'genres': ['Mystery', 'Thriller'],
  'rated': 'R',
  'metacritic': 80,
  'title': 'Memento',
  'lastupdated': '2015-08-23 00:02:21.657000000',
  'languages': ['English'],
  'writers': ['Christopher Nolan (screenplay)',
   'Jonathan Nolan (short story "Memento Mori")'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.otnemem.com',
   'viewer': {'rating': 4.1, 'numReviews': 375899, 'meter': 94},
   'dvd': datetime.datetime(2001, 9, 4, 0, 0),
   'critic': {'rating': 8.2, 'numReviews': 167, 'meter': 92},
   'boxOffice': '$23.8M',
   'consensus': "Christopher Nolan skillfully guides the audience through Memento's fractured narrative, seeping his film in existential dread.",
   'rotten': 13,
   'production': 'Newmarket Films',
   'lastUpdated': datetime.datetime(2015, 9, 12, 17, 21, 21),
   'fresh': 154},
  'poster': 'https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 1,
  'released': datetime.datetime(2001, 5, 25, 0, 0),
  'awards': {'wins': 54,
   'nominations': 44,
   'text': 'Nominated for 2 Oscars. Another 52 wins & 44 nominations.'},
  'countries': ['USA'],
  'cast': ['Guy Pearce',
   'Carrie-Anne Moss',
   'Joe Pantoliano',
   'Mark Boone Junior'],
  'directors': ['Christopher Nolan'],
  'runtime': 113},
 {'_id': ObjectId('573a13a1f29313caabd07754'),
  'fullplot': "On a hot day in a highway gas station men's room, a man Michel doesn't recognize says they went to school together. He's Harry. He suggests they have a drink, so he and his girlfriend follow Michel and his family to their summer place. Michel is amazed when Harry quotes from memory a poem Michel wrote in school. Harry thinks Michel is a great writer, and he's distressed that Michel hasn't written in years. Harry stays awhile (since his father's death, he's a man of leisure) and sets out to eliminate distractions that might keep Michel from writing. First he buys Michel a car (with air conditioning) and then suspicious things happen. Michel picks up a pen, Harry is gratified, but he's not finished being Michel's self-appointed patron.",
  'imdb': {'rating': 7.2, 'votes': 8041, 'id': 216800},
  'year': 2000,
  'plot': "Harry knew Michel in high school; they meet again by accident, Harry inserts himself in Michel's life... and things take a sinister turn.",
  'genres': ['Comedy', 'Drama', 'Mystery'],
  'rated': 'R',
  'metacritic': 75,
  'title': 'With a Friend Like Harry...',
  'lastupdated': '2015-08-18 00:34:00.783000000',
  'languages': ['French', 'Spanish'],
  'writers': ['Dominik Moll (scenario)',
   'Gilles Marchand (scenario)',
   'Francis Villain (poem)'],
  'type': 'movie',
  'tomatoes': {'website': 'http://www.diaphana.fr/harry/',
   'viewer': {'rating': 3.6, 'numReviews': 4371, 'meter': 80},
   'dvd': datetime.datetime(2001, 10, 26, 0, 0),
   'critic': {'rating': 7.5, 'numReviews': 90, 'meter': 96},
   'boxOffice': '$3.4M',
   'consensus': "A darkly funny thriller that's reminiscent of Hitchcock.",
   'rotten': 4,
   'production': 'Miramax Films',
   'lastUpdated': datetime.datetime(2015, 9, 15, 18, 25, 44),
   'fresh': 86},
  'poster': 'https://m.media-amazon.com/images/M/MV5BMTgxMTE4MTYzNl5BMl5BanBnXkFtZTYwNTE4OTI5._V1_SY1000_SX677_AL_.jpg',
  'num_mflix_comments': 2,
  'released': datetime.datetime(2001, 6, 15, 0, 0),
  'awards': {'wins': 8,
   'nominations': 14,
   'text': 'Nominated for 1 BAFTA Film Award. Another 7 wins & 14 nominations.'},
  'countries': ['France'],
  'cast': ['Laurent Lucas',
   'Sergi Lèpez',
   'Mathilde Seigner',
   'Sophie Guillemin'],
  'directors': ['Dominik Moll'],
  'runtime': 117}]

#### 논리 연산자

`$and`, `$or`, `$not`

`$nor`: 들어 있는 조건을 모두 만족하지 않을 때

In [ ]:
# 여기에 코드를 입력하세요.

### `$group`

$group은 SQL의 GROUP BY처럼 데이터를 특정 기준으로 묶어 집계(Aggregation)를 수행합니다.
MongoDB에서는 그룹 기준이 `_id` 필드이며, 계산된 필드를 새로운 key로 추가할 수 있습니다.

자주 사용하는 집계 연산자:
  - $sum : 합계 (count 용도로도 사용)

  - $avg : 평균

  - $min : 최소값

  - $max : 최대값

주의사항:
  - _id 값을 null로 설정하면 전체 집계가 가능함 (ex: 전체 평균)
  - $group 내부에서는 원본 문서의 필드를 직접 사용하려면 `$필드명` 으로 참조해야 함

In [54]:
# 여기에 코드를 입력하세요.
res_1=movies.aggregate([
    {
        "$group":{
            "_id":"$year",
            "movie_cnt":{"$sum":1}
        }
    }
])

res_2 = movies.aggregate([
    {
        "$group":{
            "_id":"$year",
            "rating_avg":{"$avg":"$imdb.rating"}
        }
    },
    {"$sort":{"rating_avg":-1}}
])
display(list(res_2))

[{'_id': '2006è2007', 'rating_avg': 9.0},
 {'_id': '1995è', 'rating_avg': 9.0},
 {'_id': '1999è', 'rating_avg': 8.9},
 {'_id': '1987è', 'rating_avg': 8.9},
 {'_id': '2007è', 'rating_avg': 8.533333333333333},
 {'_id': '2006è2012', 'rating_avg': 8.5},
 {'_id': '1996è', 'rating_avg': 8.4},
 {'_id': '2003è', 'rating_avg': 8.4},
 {'_id': '2005è', 'rating_avg': 8.4},
 {'_id': '2015è', 'rating_avg': 8.4},
 {'_id': '2009è', 'rating_avg': 8.3},
 {'_id': '1994è1998', 'rating_avg': 8.2},
 {'_id': '2010è', 'rating_avg': 8.2},
 {'_id': '1981è', 'rating_avg': 8.0},
 {'_id': '1988è', 'rating_avg': 7.85},
 {'_id': '2011è', 'rating_avg': 7.75},
 {'_id': '1986è', 'rating_avg': 7.7},
 {'_id': 1925, 'rating_avg': 7.684615384615385},
 {'_id': 1928, 'rating_avg': 7.684210526315789},
 {'_id': 1921, 'rating_avg': 7.68},
 {'_id': 1922, 'rating_avg': 7.6000000000000005},
 {'_id': 1924, 'rating_avg': 7.588888888888889},
 {'_id': 1939, 'rating_avg': 7.586206896551724},
 {'_id': 1927, 'rating_avg': 7.545454545454546},
 {'_id': 1926, 'rating_avg': 7.522222222222222},
 {'_id': '2012è', 'rating_avg': 7.5},
 {'_id': '2000è', 'rating_avg': 7.5},
 {'_id': '2002è', 'rating_avg': 7.5},
 {'_id': 1946, 'rating_avg': 7.4363636363636365},
 {'_id': 1923, 'rating_avg': 7.416666666666667},
 {'_id': 1903, 'rating_avg': 7.4},
 {'_id': 1932, 'rating_avg': 7.3839999999999995},
 {'_id': 1944, 'rating_avg': 7.383333333333334},
 {'_id': 1952, 'rating_avg': 7.375862068965517},
 {'_id': 1941, 'rating_avg': 7.358064516129032},
 {'_id': 1919, 'rating_avg': 7.35},
 {'_id': 1962, 'rating_avg': 7.342857142857143},
 {'_id': 1954, 'rating_avg': 7.334375},
 {'_id': 1948, 'rating_avg': 7.33},
 {'_id': 1947, 'rating_avg': 7.321621621621621},
 {'_id': 1965, 'rating_avg': 7.318},
 {'_id': 1955, 'rating_avg': 7.3160493827160495},
 {'_id': 1938, 'rating_avg': 7.3159090909090905},
 {'_id': 1931, 'rating_avg': 7.308333333333334},
 {'_id': 1961, 'rating_avg': 7.304255319148936},
 {'_id': 1937, 'rating_avg': 7.3},
 {'_id': 1911, 'rating_avg': 7.3},
 {'_id': 1943, 'rating_avg': 7.294444444444445},
 {'_id': 1964, 'rating_avg': 7.289380530973451},
 {'_id': 1942, 'rating_avg': 7.288888888888888},
 {'_id': 1933, 'rating_avg': 7.285185185185185},
 {'_id': 1959, 'rating_avg': 7.284269662921348},
 {'_id': 1949, 'rating_avg': 7.284126984126984},
 {'_id': 1934, 'rating_avg': 7.28125},
 {'_id': 1951, 'rating_avg': 7.280952380952381},
 {'_id': '2014è', 'rating_avg': 7.25},
 {'_id': 1936, 'rating_avg': 7.25},
 {'_id': 1945, 'rating_avg': 7.246153846153847},
 {'_id': 1940, 'rating_avg': 7.241935483870968},
 {'_id': 1971, 'rating_avg': 7.241379310344827},
 {'_id': 1960, 'rating_avg': 7.238709677419355},
 {'_id': 1957, 'rating_avg': 7.216853932584269},
 {'_id': 1929, 'rating_avg': 7.209999999999999},
 {'_id': 1974, 'rating_avg': 7.205504587155963},
 {'_id': '1997è', 'rating_avg': 7.2},
 {'_id': '2006è', 'rating_avg': 7.2},
 {'_id': 1917, 'rating_avg': 7.2},
 {'_id': 1958, 'rating_avg': 7.193478260869565},
 {'_id': 1956, 'rating_avg': 7.188750000000001},
 {'_id': 1953, 'rating_avg': 7.182926829268292},
 {'_id': 1950, 'rating_avg': 7.176811594202898},
 {'_id': 1935, 'rating_avg': 7.159999999999999},
 {'_id': 1963, 'rating_avg': 7.1595959595959595},
 {'_id': 1968, 'rating_avg': 7.146428571428571},
 {'_id': 1930, 'rating_avg': 7.1000000000000005},
 {'_id': 1912, 'rating_avg': 7.1},
 {'_id': 1967, 'rating_avg': 7.098148148148148},
 {'_id': 1972, 'rating_avg': 7.095419847328245},
 {'_id': 1966, 'rating_avg': 7.082758620689655},
 {'_id': 1969, 'rating_avg': 7.082051282051283},
 {'_id': 1977, 'rating_avg': 7.079699248120301},
 {'_id': 1973, 'rating_avg': 7.069918699186992},
 {'_id': 1975, 'rating_avg': 7.058035714285714},
 {'_id': 1970, 'rating_avg': 7.046875},
 {'_id': 2015, 'rating_avg': 6.94197247706422},
 {'_id': 1976, 'rating_avg': 6.939370078740157},
 {'_id': 1979, 'rating_avg': 6.938571428571429},
 {'_id': 1914, 'rating_avg': 6.8999999999999995},
 {'_id': 1920, 'rating_avg': 6.8500000000000005},
 {'_id': 1983, 'rating_avg': 6.828488372093023},
 {'_id': 1982, 'rating_avg': 6.804864864864865},
 {'_id': 1894, 'rating_avg': 6.8},
 {'_id': 1978, 'rating_avg': 6.786466165413534},
 {'_id': 1985, 'rating_avg': 6.753921568627451},
 {'_id': 1989, 'rating_avg': 6.722950819672132},
 {'_id': 1992, 'rating_avg': 6.720486111111111},
 {'_id': 1981, 'rating_avg': 6.711173184357541},
 {'_id': 1990, 'rating_avg': 6.66639344262295},
 {'_id': 1998, 'rating_avg': 6.663949275362318},
 {'_id': 1915, 'rating_avg': 6.659999999999999},
 {'_id': 1980, 'rating_avg': 6.6596590909090905},
 {'_id': 1987, 'rating_avg': 6.658577405857741},
 {'_id': 1984, 'rating_avg': 6.657345971563982},
 {'_id': 1916, 'rating_avg': 6.65},
 {'_id': 2004, 'rating_avg': 6.648852901484481},
 {'_id': 1986, 'rating_avg': 6.638349514563107},
 {'_id': 1995, 'rating_avg': 6.6343434343434335},
 {'_id': 1993, 'rating_avg': 6.632191780821917},
 {'_id': 1997, 'rating_avg': 6.631877729257642},
 {'_id': 1994, 'rating_avg': 6.630817610062893},
 {'_id': 1999, 'rating_avg': 6.619003690036901},
 {'_id': 1991, 'rating_avg': 6.618650793650794},
 {'_id': 2006, 'rating_avg': 6.618364928909952},
 {'_id': 2007, 'rating_avg': 6.607224770642202},
 {'_id': 1918, 'rating_avg': 6.6},
 {'_id': 1909, 'rating_avg': 6.6},
 {'_id': 2005, 'rating_avg': 6.591292875989446},
 {'_id': 1996, 'rating_avg': 6.5879350348027845},
 {'_id': 2001, 'rating_avg': 6.584031007751937},
 {'_id': 2003, 'rating_avg': 6.577929984779299},
 {'_id': 2008, 'rating_avg': 6.573243801652892},
 {'_id': 1988, 'rating_avg': 6.569433962264151},
 {'_id': 2014, 'rating_avg': 6.5637478108581435},
 {'_id': 2002, 'rating_avg': 6.561679389312976},
 {'_id': 2000, 'rating_avg': 6.539805825242718},
 {'_id': 2010, 'rating_avg': 6.5279669762641905},
 {'_id': 2009, 'rating_avg': 6.517979797979798},
 {'_id': 2011, 'rating_avg': 6.491538461538461},
 {'_id': 2013, 'rating_avg': 6.48876127973749},
 {'_id': 2012, 'rating_avg': 6.478068592057761},
 {'_id': 1893, 'rating_avg': 6.2},
 {'_id': 1913, 'rating_avg': 6.0},
 {'_id': 1896, 'rating_avg': 5.9},
 {'_id': 1891, 'rating_avg': 4.9},
 {'_id': 2016, 'rating_avg': None}]

### `$project`

`$project`는 SQL의 SELECT처럼 원하는 필드만 반환하거나 새 필드를 계산하는 단계입니다. 4일차에 진행했던 `projection`과 동일한 개념입니다.

기능:
  - 필드 포함/제외 (1: 포함, 0: 제외)

  - 필드 이름 변경

  - 새로운 계산 필드 생성(산술 연산 가능)

  - 중첩된 필드 접근 (ex. imdb.rating)

주의:
  - `_id`는 기본적으로 항상 포함되므로 제외하려면 `_id: 0` 해야 함

In [57]:
# 여기에 코드를 입력하세요.
result = movies.aggregate([
    {
        "$project":{
            "title":1,
            "score":{
                "$multiply":["$imdb.rating",10]
            }
        }
    },{"$limit":10}
])
display(list(result))

[{'_id': ObjectId('573a1390f29313caabcd4135'),
  'title': 'Blacksmith Scene',
  'score': 62.0},
 {'_id': ObjectId('573a1390f29313caabcd42e8'),
  'title': 'The Great Train Robbery',
  'score': 74.0},
 {'_id': ObjectId('573a1390f29313caabcd4323'),
  'title': 'The Land Beyond the Sunset',
  'score': 71.0},
 {'_id': ObjectId('573a1390f29313caabcd446f'),
  'title': 'A Corner in Wheat',
  'score': 66.0},
 {'_id': ObjectId('573a1390f29313caabcd4803'),
  'title': 'Winsor McCay, the Famous Cartoonist of the N.Y. Herald and His Moving Comics',
  'score': 73.0},
 {'_id': ObjectId('573a1390f29313caabcd4eaf'),
  'title': 'Traffic in Souls',
  'score': 60},
 {'_id': ObjectId('573a1390f29313caabcd50e5'),
  'title': 'Gertie the Dinosaur',
  'score': 73.0},
 {'_id': ObjectId('573a1390f29313caabcd516c'),
  'title': 'In the Land of the Head Hunters',
  'score': 58.0},
 {'_id': ObjectId('573a1390f29313caabcd5293'),
  'title': 'The Perils of Pauline',
  'score': 76.0},
 {'_id': ObjectId('573a1390f29313caabcd548c'),
  'title': 'The Birth of a Nation',
  'score': 68.0}]